// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
import { createHash, randomUUID } from 'node:crypto';
import { chmod, link, lstat, mkdir, readFile, readdir, realpath, rename, unlink, writeFile } from 'node:fs/promises';
import { dirname, isAbsolute, join, relative, resolve, sep } from 'node:path';
import { analyzeSource } from './analyzeSource.js';
import { renderSource, type SourceRenderOptions } from './renderSource.js';

const marker = '// @generated by Cratis. Source: TypeScript program. Hash: ';
const digest = (text: string): string => createHash('sha256').update(text).digest('hex').toUpperCase();
const content = (text: string): string => `${marker}${digest(text)}\n${text}`;
const owned = (text: string): boolean => {
    const first = text.indexOf('\n');
    return first > 0 && text.slice(0, first) === `${marker}${digest(text.slice(first + 1))}`;
};
export interface SourceGeneratorOptions extends SourceRenderOptions {
    readonly project: string;
    readonly artifacts: string;
    readonly output: string;
}
/** Analyze source once, preflight owned paths and publish only changed files. Never delete handwritten files. */
export async function generateFromSource(options: SourceGeneratorOptions): Promise<readonly string[]> {
    if (![options.project, options.artifacts, options.output].every(isAbsolute)) throw new Error('Project, artifacts and output must be absolute paths');
    const output = resolve(options.output);
    const root = await lstat(output);
    if (!root.isDirectory() || root.isSymbolicLink() || await realpath(output) !== output) throw new Error('Output must be an existing real directory');
    const artifacts = await realpath(options.artifacts);
    if (!(await lstat(artifacts)).isDirectory()) throw new Error('Artifacts must be a directory');
    const rendered = renderSource(analyzeSource(options.project, artifacts), options);
    const files = new Map([...rendered].map(([path, text]) => [path, content(text)]));
    const directories = new Set([...files.keys()].map(dirname));
    for (const directory of directories) {
        const names = [...files.keys()].filter(path => dirname(path) === directory).map(path => `export * from './${path.slice(directory === '.' ? 0 : directory.length + 1).replace(/\.ts$/, '')}';`).sort();
        files.set(join(directory, 'index.ts'), content(names.join('\n') + '\n'));
    }
    const existing = new Map<string, string>();
    const visit = async (directory: string): Promise<void> => {
        for (const entry of await readdir(directory, { withFileTypes: true })) {
            const path = join(directory, entry.name);
            if (entry.isSymbolicLink()) throw new Error(`Symlink in output: ${path}`);
            if (entry.isDirectory()) await visit(path);
            else if (entry.isFile() && entry.name.endsWith('.ts')) existing.set(relative(output, path), await readFile(path, 'utf8'));
        }
    };
    await visit(output);
    for (const [path, text] of existing) {
        if (files.has(path) && text !== files.get(path) && !owned(text)) throw new Error(`Refusing to overwrite handwritten or edited file: ${path}`);
        if (!files.has(path) && text.startsWith(marker) && !owned(text)) throw new Error(`Refusing to delete edited generated file: ${path}`);
    }
    const changed: string[] = [];
    try {
    for (const [path, text] of files) {
        if (existing.get(path) === text) continue;
        const destination = join(output, path);
        if (!destination.startsWith(output + sep) || path.includes('..')) throw new Error(`Unsafe output: ${path}`);
        await mkdir(dirname(destination), { recursive: true });
        const current = existing.get(path);
        const actual = await readFile(destination, 'utf8').catch(error => {
            if ((error as NodeJS.ErrnoException).code === 'ENOENT') return undefined;
            throw error;
        });
        if (current !== actual) throw new Error(`Output changed during generation: ${path}`);
        const temporary = join(dirname(destination), `.arc-${randomUUID()}.tmp`);
        await writeFile(temporary, text, { flag: 'wx', mode: current === undefined ? 0o666 & ~process.umask() : (await lstat(destination)).mode & 0o777 });
        try {
            if (current === undefined) await link(temporary, destination);
            else { await chmod(temporary, (await lstat(destination)).mode & 0o777); await rename(temporary, destination); }
        } finally { await unlink(temporary).catch(error => { if ((error as NodeJS.ErrnoException).code !== 'ENOENT') throw error; }); }
        changed.push(destination);
    }
    for (const [path, text] of existing) {
        if (!files.has(path) && owned(text)) {
            const destination = join(output, path);
            if (await readFile(destination, 'utf8') !== text) throw new Error(`Output changed during cleanup: ${path}`);
            await unlink(destination);
            changed.push(destination);
        }
    }
    } catch (error) {
        if (changed.length) throw new AggregateError([error], `Source generation partially committed: ${changed.join(', ')}`, { cause: error });
        throw error;
    }
    return changed;
}
