// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
import { createHash, randomUUID } from 'node:crypto';
import { chmod, link, lstat, mkdir, readFile, readdir, realpath, rename, unlink, writeFile } from 'node:fs/promises';
import { basename, dirname, isAbsolute, join, relative, resolve, sep } from 'node:path';
import { analyzeSource } from './analyzeSource.js';
import { sourceProgram } from './sourceProgram.js';
import { filename, queryClassName, renderSource, type SourceRenderOptions } from './renderSource.js';
import { metadataCollector } from './renderGeneratedMetadata.js';
import { preflightGeneratedMetadata, publishGeneratedMetadata } from './publishGeneratedMetadata.js';

const marker = '// @generated by Cratis. Source: ';
const digest = (text: string): string => createHash('sha256').update(text).digest('hex').toUpperCase();
const content = (source: string, text: string): string => `${marker}${source}. Time: ${new Date().toISOString().replace('Z', '0000Z')}. Hash: ${digest(text)}\n${text}`;
const owned = (text: string): boolean => {
    const first = text.indexOf('\n');
    return first > 0 && text.slice(0, first).startsWith(marker) &&
        text.slice(0, first).endsWith(`. Hash: ${digest(text.slice(first + 1))}`);
};
const bodyHash = (text: string): string | undefined => owned(text) ? digest(text.slice(text.indexOf('\n') + 1)) : undefined;
export interface SourceGeneratorOptions extends SourceRenderOptions {
    readonly project: string;
    readonly artifacts: string;
    readonly output: string;
    readonly rootNamespace?: string;
    readonly skipIndexGeneration?: boolean;
    readonly skipOutputDeletion?: boolean;
    readonly emitInterfaces?: boolean;
    /** Absolute path of an optional source-generated server metadata module. */
    readonly metadata?: string;
    /** Opt into source-inferred bindings even when this invocation does not publish metadata. */
    readonly generatedMetadata?: boolean;
}
/** Analyze source once, preflight owned paths and publish only changed files. Never delete handwritten files. */
export async function generateFromSource(options: SourceGeneratorOptions): Promise<readonly string[]> {
    if (![options.project, options.artifacts, options.output, ...options.metadata ? [options.metadata] : []].every(isAbsolute))
        throw new Error('Project, artifacts, output and metadata must be absolute paths');
    const requested = resolve(options.output);
    const root = await lstat(requested);
    if (!root.isDirectory()) throw new Error('Output must be an existing directory');
    const output = await realpath(requested);
    const artifacts = await realpath(options.artifacts);
    if (!(await lstat(artifacts)).isDirectory()) throw new Error('Artifacts must be a directory');
    if (options.metadata) await preflightGeneratedMetadata(options.metadata);
    const program = sourceProgram(options.project);
    const collector = options.metadata ? metadataCollector(program, options.metadata) : undefined;
    const analysis = analyzeSource(options.project, artifacts, options.rootNamespace,
        !!collector || options.generatedMetadata === true, program, collector?.visit);
    const metadata = collector?.render(options.project, artifacts);
    const rendered = renderSource(analysis, options);
    const sources = new Map([
        ...analysis.models.map(model => [filename(model.name, model.namespace, options),
            [model.namespace, model.name].filter(Boolean).join('.')] as const),
        ...analysis.operations.map(operation => [filename(operation.kind === 'command' ? operation.name : queryClassName(operation.name), operation.namespace, options),
            [operation.namespace, operation.owner, ...(operation.kind === 'command' ? [] : [operation.name])].filter(Boolean).join('.')] as const)
    ]);
    const files = new Map<string, { source: string; text: string; handwritten?: boolean }>([...rendered].map(([path, text]) => [path, { source: sources.get(path) ?? path, text }]));
    const directories = new Set([...files.keys()].map(dirname));
    if (!options.skipIndexGeneration) for (const directory of directories) {
        const names = [...files.keys()].filter(path => dirname(path) === directory).map(path => `export * from './${path.slice(directory === '.' ? 0 : directory.length + 1).replace(/\.ts$/, '')}';`).sort();
        files.set(join(directory, 'index.ts'), { source: '', text: names.join('\n') + '\n' });
    }
    const existing = new Map<string, string>();
    const visit = async (directory: string): Promise<void> => {
        for (const entry of await readdir(directory, { withFileTypes: true })) {
            const path = join(directory, entry.name);
            if (entry.isSymbolicLink()) throw new Error(`Symlink in output: ${path}`);
            if (entry.isDirectory()) await visit(path);
            else if (entry.isFile() && entry.name.endsWith('.ts')) existing.set(relative(output, path), await readFile(path, 'utf8'));
        }
    };
    await visit(output);
    for (const [path, text] of existing) {
        if (basename(path) === 'index.ts' && text.startsWith(marker) && !owned(text))
            throw new Error(`Refusing to overwrite edited generated barrel: ${path}`);
        if (files.has(path) && basename(path) === 'index.ts') continue;
        if (files.has(path) && bodyHash(text) !== digest(files.get(path)!.text) && !owned(text)) throw new Error(`Refusing to overwrite handwritten or edited file: ${path}`);
        if (!files.has(path) && !options.skipOutputDeletion && text.startsWith(marker) && !owned(text)) throw new Error(`Refusing to delete edited generated file: ${path}`);
    }
    // Preflight barrels before any write. Handwritten barrels retain all lines except references to deleted owned files.
    for (const [path, previous] of existing) {
        if (basename(path) !== 'index.ts') continue;
        const entry = files.get(path);
        const body = owned(previous) ? previous.slice(previous.indexOf('\n') + 1) : previous;
        const retained = body.split('\n').filter(line => {
            const match = /^export \* from '\.\/([^']+)';$/.exec(line);
            if (!match) return !!line.trim();
            const target = join(dirname(path), `${match[1]}.ts`);
            return !(!options.skipOutputDeletion && !files.has(target) && owned(existing.get(target) ?? ''));
        });
        if (owned(previous)) {
            if (entry) entry.text = [...retained.filter(line => {
                const match = /^export \* from '\.\/([^']+)';$/.exec(line);
                return !match || !owned(existing.get(join(dirname(path), `${match[1]}.ts`)) ?? '');
            }), ...entry.text.trimEnd().split('\n')].join('\n') + '\n';
        } else {
            const text = retained.join('\n') + '\n';
            if (entry) files.delete(path);
            if (text !== previous) files.set(path, { source: '', text, handwritten: true });
        }
    }
    const changed: string[] = [];
    try {
    for (const [path, entry] of files) {
        const previous = existing.get(path);
        const text = entry.handwritten ? entry.text : previous && bodyHash(previous) === digest(entry.text) ? previous : content(entry.source, entry.text);
        if (previous === text) continue;
        const destination = join(output, path);
        if (!destination.startsWith(output + sep) || path.includes('..')) throw new Error(`Unsafe output: ${path}`);
        await mkdir(dirname(destination), { recursive: true });
        const current = existing.get(path);
        const actual = await readFile(destination, 'utf8').catch(error => {
            if ((error as NodeJS.ErrnoException).code === 'ENOENT') return undefined;
            throw error;
        });
        if (current !== actual) throw new Error(`Output changed during generation: ${path}`);
        const temporary = join(dirname(destination), `.arc-${randomUUID()}.tmp`);
        await writeFile(temporary, text, { flag: 'wx', mode: current === undefined ? 0o666 & ~process.umask() : (await lstat(destination)).mode & 0o777 });
        try {
            if (current === undefined) await link(temporary, destination);
            else { await chmod(temporary, (await lstat(destination)).mode & 0o777); await rename(temporary, destination); }
        } finally { await unlink(temporary).catch(error => { if ((error as NodeJS.ErrnoException).code !== 'ENOENT') throw error; }); }
        changed.push(destination);
    }
    for (const [path, text] of existing) {
        if (!options.skipOutputDeletion && !files.has(path) && owned(text)) {
            const destination = join(output, path);
            if (await readFile(destination, 'utf8') !== text) throw new Error(`Output changed during cleanup: ${path}`);
            await unlink(destination);
            changed.push(destination);
        }
    }
    if (options.metadata && metadata && await publishGeneratedMetadata(options.metadata, metadata)) changed.push(options.metadata);
    } catch (error) {
        if (changed.length) throw new AggregateError([error], `Source generation partially committed: ${changed.join(', ')}`, { cause: error });
        throw error;
    }
    return changed;
}
