// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
import { createHash } from 'node:crypto';

/** Prefix identifying files owned by the proxy generator. */
export const marker = '// @generated by Cratis. Source: ';
/** Exact header of generated server metadata before its integrity hash is added. */
export const metadataMarker = '// @generated by Cratis. Regenerate with arc-proxygenerator --metadata.';
export const metadataHeader = `// Copyright (c) Cratis. All rights reserved.\n// Licensed under the MIT license. See LICENSE file in the project root for full license information.\n${metadataMarker}`;
/** Hash used to detect changes to generated file bodies. */
export const digest = (text: string): string => createHash('sha256').update(text).digest('hex').toUpperCase();
/** Wrap generated content with its source and integrity metadata. */
export const content = (source: string, text: string): string =>
    `${marker}${source}. Time: ${new Date().toISOString().replace('Z', '0000Z')}. Hash: ${digest(text)}\n${text}`;
/** Check whether a file has an intact generated-file marker. */
export const owned = (text: string): boolean => {
    const first = text.indexOf('\n');
    return first > 0 && text.slice(0, first).startsWith(marker) &&
        text.slice(0, first).endsWith(`. Hash: ${digest(text.slice(first + 1))}`);
};
/** Hash the body only when the generated file is intact. */
export const bodyHash = (text: string): string | undefined => owned(text) ? digest(text.slice(text.indexOf('\n') + 1)) : undefined;
/** Check the exact metadata header and the integrity hash of the unstamped file. */
export const metadataOwned = (text: string): boolean => {
    if (!text.startsWith(`${metadataHeader} Hash: `)) return false;
    const lineEnd = text.indexOf('\n', metadataHeader.length);
    if (lineEnd < 0) return false;
    const stamp = text.slice(metadataHeader.length, lineEnd);
    if (!/^ Hash: [a-f0-9]{64}$/.test(stamp)) return false;
    const unstamped = `${metadataHeader}${text.slice(lineEnd)}`;
    return createHash('sha256').update(unstamped).digest('hex') === stamp.slice(' Hash: '.length);
};
