// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
import { createHash } from 'node:crypto';

/** Prefix identifying files owned by the proxy generator. */
export const marker = '// @generated by Cratis. Source: ';
/** Hash used to detect changes to generated file bodies. */
export const digest = (text: string): string => createHash('sha256').update(text).digest('hex').toUpperCase();
/** Wrap generated content with its source and integrity metadata. */
export const content = (source: string, text: string): string =>
    `${marker}${source}. Time: ${new Date().toISOString().replace('Z', '0000Z')}. Hash: ${digest(text)}\n${text}`;
/** Check whether a file has an intact generated-file marker. */
export const owned = (text: string): boolean => {
    const first = text.indexOf('\n');
    return first > 0 && text.slice(0, first).startsWith(marker) &&
        text.slice(0, first).endsWith(`. Hash: ${digest(text.slice(first + 1))}`);
};
/** Hash the body only when the generated file is intact. */
export const bodyHash = (text: string): string | undefined => owned(text) ? digest(text.slice(text.indexOf('\n') + 1)) : undefined;
