// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
import { dirname, resolve } from 'node:path';
import ts from 'typescript';
import { discoveryFiles } from '@cratis/arc.core';
import { MetadataImports } from './MetadataImports.js';
import { renderArtifactMetadata } from './renderArtifactMetadata.js';

/** Analyze a TypeScript project and render a deterministic server metadata module. */
export function renderGeneratedMetadata(project: string, artifacts: string, output: string): string {
    const configuration = ts.readConfigFile(project, ts.sys.readFile);
    if (configuration.error) throw new Error(ts.flattenDiagnosticMessageText(configuration.error.messageText, '\n'));
    const parsed = ts.parseJsonConfigFileContent(configuration.config, ts.sys, dirname(resolve(project)), undefined, resolve(project));
    if (parsed.errors.length) throw new Error(ts.formatDiagnosticsWithColorAndContext(parsed.errors, {
        getCanonicalFileName: file => file, getCurrentDirectory: ts.sys.getCurrentDirectory, getNewLine: () => '\n'
    }));
    const program = ts.createProgram(parsed.fileNames, parsed.options);
    const checker = program.getTypeChecker();
    const imports = new MetadataImports(checker, output);
    const entries: string[] = [];
    for (const path of discoveryFiles(resolve(artifacts))) {
        const file = program.getSourceFile(path);
        if (!file) throw new Error(`${path}: not included in ${project}; regenerate artifact metadata with the correct project`);
        const module = checker.getSymbolAtLocation(file);
        const exported = new Set(module ? checker.getExportsOfModule(module).map(symbol =>
            symbol.flags & ts.SymbolFlags.Alias ? checker.getAliasedSymbol(symbol) : symbol) : []);
        for (const declaration of file.statements) {
            if (!ts.isClassDeclaration(declaration) || !declaration.name || !exported.has(checker.getSymbolAtLocation(declaration.name)!)) continue;
            const rendered = renderArtifactMetadata(declaration, checker, imports);
            if (rendered) entries.push(rendered);
        }
    }
    if (!entries.length) throw new Error(`No Arc artifacts below ${artifacts} in ${project}`);
    const functions = ['abortSignal', 'commandContext', 'commandReadModel', 'provided'].filter(name =>
        entries.some(entry => entry.includes(`${name}(`)));
    return `// Copyright (c) Cratis. All rights reserved.\n// Licensed under the MIT license. See LICENSE file in the project root for full license information.\n` +
        `// @generated by Cratis. Regenerate with arc-proxygenerator --metadata.\n` +
        `import { ${functions.map(name => `${name}, `).join('')}type GeneratedMetadata } from '@cratis/arc.core';\n` +
        `${imports.render()}\n\nexport const metadata = { version: 1, artifacts: [\n    ${entries.join(',\n    ')}\n] } satisfies GeneratedMetadata;\n`;
}
