// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
import assert from 'node:assert/strict';
import { spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { createRequire } from 'node:module';
import { cp, mkdir, readFile, readdir, writeFile } from 'node:fs/promises';
import { basename, join, resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
import { build } from 'esbuild';
import { generateFromSource } from '@cratis/arc.proxygenerator';
import { clientTest, scratch } from '../Client/scratch.mjs';
import { dotnetOptions, dotnetSource, fixture, generateBoth, recaptureCommand, root, run, typescriptOptions } from './generate.mjs';

const require = createRequire(import.meta.url);
const snapshots = join(fixture, 'Snapshots');
const expectedFiles = ['All.ts', 'Detail.ts', 'Listing.ts', 'Notice.ts', 'Observe.ts', 'Register.ts', 'Status.ts', 'UrgentNotice.ts', 'index.ts']
    .map(file => `ProxyComparison/${file}`);

/** Replace only the timestamp in the first provenance line; retain every body byte, source and hash. */
export function stableBytes(bytes) {
    const end = bytes.indexOf(10);
    const header = bytes.subarray(0, end).toString('utf8');
    if (!header.startsWith('// @generated by Cratis.')) return bytes;
    assert.match(header, /^\/\/ @generated by Cratis\. Source: .*\. Time: \d{4}-\d\d-\d\dT\d\d:\d\d:\d\d\.\d{7}Z\. Hash: [A-F0-9]{64}$/);
    const body = bytes.subarray(end + 1);
    assert.equal(header.slice(-64), createHash('sha256').update(body).digest('hex').toUpperCase(), 'Provenance body hash must be valid');
    return Buffer.concat([Buffer.from(header.replace(/Time: .*?\. Hash:/, 'Time: <timestamp>. Hash:')), bytes.subarray(end)]);
}

export async function filesIn(directory, prefix = '') {
    const files = [];
    for (const entry of await readdir(directory, { withFileTypes: true })) {
        assert.ok(entry.isFile() || entry.isDirectory(), `Unexpected entry: ${entry.name}`);
        const relative = `${prefix}${entry.name}`;
        if (entry.isDirectory()) files.push(...await filesIn(join(directory, entry.name), `${relative}/`));
        else files.push(relative);
    }
    return files.sort();
}

/** Exit 1 is the expected 'different bytes' result, not an ignored command failure. */
async function rawDiff(left, right) {
    const files = [...new Set([...await filesIn(left), ...await filesIn(right)])].sort();
    let patch = '';
    for (const file of files) {
        const result = spawnSync('diff', ['-U', '0', '-N', '-L', `DotNET/${file}`, '-L', `TypeScript/${file}`, join(left, file), join(right, file)],
            { encoding: 'utf8', timeout: 10000 });
        assert.equal(result.error, undefined);
        assert.ok(result.status === 0 || result.status === 1, result.stderr);
        patch += result.stdout;
    }
    return patch;
}

async function verifyInventory(dotnet, typescript) {
    const inventory = JSON.parse(await readFile(join(fixture, 'differences.json'), 'utf8'));
    const different = [];
    for (const file of expectedFiles) {
        if (!stableBytes(await readFile(join(dotnet, file))).equals(stableBytes(await readFile(join(typescript, file))))) different.push(file);
    }
    assert.deepEqual(Object.keys(inventory.files).sort(), different, 'Every non-timestamp difference needs an inventory entry');
    for (const [id, reason] of Object.entries(inventory.reasons)) {
        assert.ok(['intentional', 'knownDefect', 'knownLimitation'].includes(reason.category), `Missing category for ${id}`);
        assert.ok(reason.description?.length > 20, `Missing reason for ${id}`);
        if (reason.category !== 'intentional') assert.match(reason.issue, /^https:\/\/github\.com\/Cratis\/[\w.]+\/issues\/\d+$/);
    }
    for (const ids of [...Object.values(inventory.files), inventory.limitations]) {
        assert.ok(ids.length > 0);
        for (const id of ids) assert.ok(inventory.reasons[id], `Missing reason for ${id}`);
    }
    for (const id of inventory.limitations) assert.equal(inventory.reasons[id].category, 'knownLimitation');
}

/** Hash exact source bytes and the ordered generator argument array, not incidental script formatting. */
export function fingerprintDotnetInputs(source, options) {
    const sha256 = value => createHash('sha256').update(value).digest('hex');
    return { sourceSha256: sha256(source), optionsSha256: sha256(JSON.stringify(options)) };
}

export function verifyDotnetInputs(recorded, current) {
    for (const key of ['sourceSha256', 'optionsSha256']) {
        assert.equal(recorded[key], current[key], `.NET snapshot ${key} is stale. Recapture with .NET: ${recaptureCommand}`);
    }
}

async function compileAndExercise(directory, regenerateDotnet) {
    // Same strict browser-client compilation as ContractTests/Client. The .NET template uses value imports
    // for types, so verbatimModuleSyntax is deliberately off; these sources are compiled without rewriting.
    for (const family of ['DotNET', 'TypeScript']) {
        const consumer = (await readFile(join(fixture, 'consumer.ts.txt'), 'utf8')).replaceAll('__FAMILY__', family);
        await writeFile(join(directory, 'src', `${family}Consumer.ts`), consumer);
    }
    await writeFile(join(directory, 'tsconfig.json'), JSON.stringify({ compilerOptions: {
        target: 'ES2022', module: 'ESNext', moduleResolution: 'Bundler', strict: true,
        skipLibCheck: false, noEmitOnError: true, noEmit: true, types: ['node'], lib: ['ES2022', 'DOM']
    }, include: ['src/**/*.ts'] }));
    run(join(root, 'node_modules/.bin/tsc'), ['-p', join(fixture, 'TypeScript/tsconfig.json')]);
    run(join(root, 'node_modules/.bin/tsc'), ['-p', join(directory, 'tsconfig.json')]);
    // Bundle only to resolve .NET's extensionless relative imports for Node; the tsc check above compiles
    // the untouched output. Separate processes prevent a shared derived-type registry masking a failure.
    for (const family of ['DotNET', 'TypeScript']) {
        const bundle = join(directory, 'dist', `${family}.js`);
        await build({ entryPoints: [join(directory, 'src', family, 'ProxyComparison/index.ts')], outfile: bundle,
            bundle: true, platform: 'node', format: 'esm', packages: 'external', target: 'es2022' });
        run(process.execPath, [join(fixture, 'runtime.mjs'), bundle, family, ...(regenerateDotnet ? ['--dotnet-server'] : [])]);
    }
}

export async function compare({ regenerateDotnet = true, capture = false } = {}) {
    assert.ok(!capture || regenerateDotnet, 'Capturing requires actual .NET regeneration');
    assert.equal(require('@cratis/arc/package.json').version, '22.45.0');
    assert.equal(require('@cratis/arc.react/package.json').version, '22.45.0');
    assert.equal(require('@cratis/fundamentals/package.json').version, '7.22.0');
    const fingerprints = fingerprintDotnetInputs(await readFile(join(root, dotnetSource)), dotnetOptions);
    const recorded = capture ? undefined : JSON.parse(await readFile(join(fixture, 'provenance.json'), 'utf8'));
    // Fail before allocating scratch or compiling: offline CI cannot regenerate changed C# inputs.
    if (recorded) verifyDotnetInputs(recorded.dotnet, fingerprints);
    const directory = await scratch();
    const output = join(directory, 'src');
    const evidence = join(root, '.ai-work/keep/proxy-comparison');
    let log;
    let patch;
    try {
        await mkdir(output);
        const dotnet = join(output, 'DotNET');
        const typescript = join(output, 'TypeScript');
        if (regenerateDotnet) ({ log } = await generateBoth(output));
        else {
            await cp(join(snapshots, 'DotNET'), dotnet, { recursive: true });
            await mkdir(typescript);
            await generateFromSource({ project: join(fixture, 'TypeScript/tsconfig.json'), artifacts: join(fixture, 'TypeScript'),
                output: typescript, ...typescriptOptions });
        }
        patch = await rawDiff(dotnet, typescript);
        for (const family of ['DotNET', 'TypeScript']) {
            const generated = join(output, family);
            assert.deepEqual(await filesIn(generated), expectedFiles, `${family} output inventory changed`);
            if (!capture) {
                assert.deepEqual(await filesIn(join(snapshots, family)), expectedFiles);
                for (const file of expectedFiles) assert.deepEqual(stableBytes(await readFile(join(generated, file))),
                    stableBytes(await readFile(join(snapshots, family, file))), `${family}/${file}: unreviewed bytes; inspect ${evidence}`);
            }
        }
        await verifyInventory(dotnet, typescript);
        await compileAndExercise(directory, regenerateDotnet);
        const provenance = {
            dotnet: { package: 'Cratis.Arc.ProxyGenerator.Build', version: '22.45.0', framework: 'net10.0',
                executable: 'tasks/net10.0/Cratis.Arc.ProxyGenerator.Build.dll',
                input: 'ContractTests/DotNET/bin/Debug/net10.0/Arc.TypeScript.HttpFixture.dll', options: dotnetOptions,
                source: dotnetSource, ...fingerprints, lock: 'ContractTests/DotNET/packages.lock.json' },
            typescript: { package: '@cratis/arc.proxygenerator', version: JSON.parse(await readFile(join(root, 'Source/Tools/ProxyGenerator/package.json'), 'utf8')).version,
                entryPoint: 'generateFromSource', project: 'ContractTests/ProxyComparison/TypeScript/tsconfig.json',
                artifacts: 'ContractTests/ProxyComparison/TypeScript', options: typescriptOptions },
            client: { '@cratis/arc': '22.45.0', '@cratis/arc.react': '22.45.0', '@cratis/fundamentals': '7.22.0' }
        };
        if (capture) {
            for (const family of ['DotNET', 'TypeScript']) await cp(join(output, family), join(snapshots, family), { recursive: true });
            await writeFile(join(fixture, 'raw.diff'), patch);
            await writeFile(join(fixture, 'provenance.json'), `${JSON.stringify(provenance, null, 2)}\n`);
        } else {
            // TypeScript's package version advances independently of these snapshots. Its captured version is
            // provenance, not a requirement to rewrite snapshots during every unrelated release.
            provenance.typescript.version = recorded.typescript.version;
            assert.deepEqual(recorded, provenance);
            assert.equal(await readFile(join(fixture, 'raw.diff'), 'utf8'), await rawDiff(join(snapshots, 'DotNET'), join(snapshots, 'TypeScript')));
        }
    } catch (error) {
        // Successful runs leave no accumulating evidence; failures retain unique diffs/logs and scratch.
        if (patch !== undefined || log !== undefined) {
            await mkdir(evidence, { recursive: true });
            if (patch !== undefined) await writeFile(join(evidence, `${basename(directory)}.diff`), patch, { flag: 'wx' });
            if (log !== undefined) await writeFile(join(evidence, `${basename(directory)}.log`), log, { flag: 'wx' });
        }
        throw error;
    }
    console.log(`Proxy comparison: 9 files per generator; bytes, inventory, compilation, hooks, routes, descriptors, hydration, validation and sorting passed (${regenerateDotnet ? 'regenerated .NET with live sorting checks' : 'captured .NET; live .NET sorting skipped'}).`);
}

if (process.argv[1] && pathToFileURL(resolve(process.argv[1])).href === import.meta.url) {
    assert.ok(process.argv.slice(2).every(argument => argument === '--capture'), 'Only --capture is supported');
    clientTest('pinned .NET and TypeScript proxy comparison', () => compare({ capture: process.argv.includes('--capture') }));
}
