// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
// Generated by yarn set-version. Do not edit.
export const packageVersion = '0.58.0';
