// @generated by Cratis. Source: ProxyComparison.Listing.All. Time: 2026-10-02T17:43:19.5340000Z. Hash: 62295E125CE69F80C53E5AF3B37B8C40039C964B91A67F637997C0F3976C4440
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { QueryFor, type QueryResultWithState, type Sorting, Paging, SortingActions, SortingActionsForQuery } from '@cratis/arc/queries';
import { useQuery, useSuspenseQuery, useQueryWithPaging, useSuspenseQueryWithPaging, type SetPage, type SetPageSize, type PerformQuery, type SetSorting, QueryWhen } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { Guid } from '@cratis/fundamentals';
import { Listing } from './Listing';

class AllSortBy {
    readonly name: SortingActionsForQuery<Listing[]>;
    readonly status: SortingActionsForQuery<Listing[]>;
    constructor(readonly query: All) {
        this.name = new SortingActionsForQuery<Listing[]>('name', query);
        this.status = new SortingActionsForQuery<Listing[]>('status', query);
    }
}
class AllSortByWithoutQuery {
    readonly name = new SortingActions('name');
    readonly status = new SortingActions('status');
}

export interface AllParameters {
    id: Guid;
}

export class All extends QueryFor<Listing[], AllParameters> {
    readonly route: string = '/api/proxy-comparison/all';
    readonly queryName: string = 'ProxyComparison.Listing.All';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: Listing[] = [];
    private readonly _sortBy: AllSortBy;
    private static readonly _sortBy: AllSortByWithoutQuery = new AllSortByWithoutQuery();

    constructor() {
        super(Listing, true);
        this._sortBy = new AllSortBy(this);
    }

    get requiredRequestParameters(): string[] {
        return [
            'id',
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
        new ParameterDescriptor('id', Guid, false),
    ];

    id!: Guid;

    get sortBy(): AllSortBy { return this._sortBy; }
    static get sortBy(): AllSortByWithoutQuery { return this._sortBy; }

    static use(args?: AllParameters, sorting?: Sorting): [QueryResultWithState<Listing[]>, PerformQuery<AllParameters>, SetSorting] {
        return useQuery<Listing[], All, AllParameters>(All, args, sorting);
    }

    static useWithPaging(pageSize: number, args?: AllParameters, sorting?: Sorting): [QueryResultWithState<Listing[]>, PerformQuery, SetSorting, SetPage, SetPageSize] {
        return useQueryWithPaging<Listing[], All>(All, new Paging(0, pageSize), args, sorting);
    }

    static useSuspense(args?: AllParameters, sorting?: Sorting): [QueryResultWithState<Listing[]>, PerformQuery<AllParameters>, SetSorting] {
        return useSuspenseQuery<Listing[], All, AllParameters>(All, args, sorting);
    }

    static useSuspenseWithPaging(pageSize: number, args?: AllParameters, sorting?: Sorting): [QueryResultWithState<Listing[]>, PerformQuery, SetSorting, SetPage, SetPageSize] {
        return useSuspenseQueryWithPaging<Listing[], All>(All, new Paging(0, pageSize), args, sorting);
    }

    static when(condition: boolean): QueryWhen<All, Listing[], AllParameters> {
        return new QueryWhen<All, Listing[], AllParameters>(All, condition);
    }
}
