// @generated by Cratis. Source: ProxyComparison.Detail. Time: 2026-10-02T14:53:03.8220000Z. Hash: EB083CE16EB7845B06C37F70EA02EC4D9BDB54179F8A3E64467299B7702BA917
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { Guid, field } from '@cratis/fundamentals';

export class Detail {
    @field(Guid)
    id!: Guid;

    @field(Date)
    created!: Date;
}
