// @generated by Cratis. Source: ProxyComparison.Listing. Time: 2026-10-02T15:23:26.2850000Z. Hash: EAAC3EB0B31A551AE2BC36EFD4D8F8EC34FCB11785A63CB982B2BEA7F1ACFBF5
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { field } from '@cratis/fundamentals';
import { Detail } from './Detail';
import { Notice } from './Notice';
import { Status } from './Status';

export class Listing {
    @field(String)
    name!: string;

    @field(Detail)
    detail!: Detail;

    @field(Notice)
    notice!: Notice;

    @field(Number)
    status!: Status;
}
