// @generated by Cratis. Source: ProxyComparison.Notice. Time: 2026-10-02T15:23:26.2860000Z. Hash: C7BFC73EC13766A0F0B09DA0E21C97DFBF0018E89CB55A81E1C560094F91BA4E
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { field } from '@cratis/fundamentals';

export class Notice {
    @field(String)
    title!: string;
}
