// @generated by Cratis. Source: ProxyComparison.Listing.Observe. Time: 2026-10-02T14:53:03.8230000Z. Hash: 4B563871A5AF1853D3C85AB5D3A3AF5882D395039B02DCAC180B733C4E641B96
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { ObservableQueryFor, type QueryResultWithState, type Sorting, Paging, SortingActions, SortingActionsForObservableQuery, type ChangeSet } from '@cratis/arc/queries';
import { useObservableQuery, useSuspenseObservableQuery, useObservableQueryWithPaging, useSuspenseObservableQueryWithPaging, type SetPage, type SetPageSize, useChangeStream, type SetSorting, ObservableQueryWhen } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { Guid } from '@cratis/fundamentals';
import { Listing } from './Listing';

class ObserveSortBy {
    readonly name: SortingActionsForObservableQuery<Listing[]>;
    readonly detail: SortingActionsForObservableQuery<Listing[]>;
    readonly notice: SortingActionsForObservableQuery<Listing[]>;
    readonly status: SortingActionsForObservableQuery<Listing[]>;
    constructor(readonly query: Observe) {
        this.name = new SortingActionsForObservableQuery<Listing[]>('name', query);
        this.detail = new SortingActionsForObservableQuery<Listing[]>('detail', query);
        this.notice = new SortingActionsForObservableQuery<Listing[]>('notice', query);
        this.status = new SortingActionsForObservableQuery<Listing[]>('status', query);
    }
}
class ObserveSortByWithoutQuery {
    readonly name = new SortingActions('name');
    readonly detail = new SortingActions('detail');
    readonly notice = new SortingActions('notice');
    readonly status = new SortingActions('status');
}

export interface ObserveParameters {
    id: Guid;
}

export class Observe extends ObservableQueryFor<Listing[], ObserveParameters> {
    readonly route: string = '/api/proxy-comparison/observe';
    readonly queryName: string = 'ProxyComparison.Listing.Observe';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: Listing[] = [];
    private readonly _sortBy: ObserveSortBy;
    private static readonly _sortBy: ObserveSortByWithoutQuery = new ObserveSortByWithoutQuery();

    constructor() {
        super(Listing, true);
        this._sortBy = new ObserveSortBy(this);
    }

    get requiredRequestParameters(): string[] {
        return [
            'id',
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
        new ParameterDescriptor('id', Guid, false),
    ];

    id!: Guid;

    get sortBy(): ObserveSortBy { return this._sortBy; }
    static get sortBy(): ObserveSortByWithoutQuery { return this._sortBy; }

    static use(args?: ObserveParameters, sorting?: Sorting): [QueryResultWithState<Listing[]>, SetSorting] {
        return useObservableQuery<Listing[], Observe, ObserveParameters>(Observe, args, sorting);
    }

    static useWithPaging(pageSize: number, args?: ObserveParameters, sorting?: Sorting): [QueryResultWithState<Listing[]>, SetSorting, SetPage, SetPageSize] {
        return useObservableQueryWithPaging<Listing[], Observe>(Observe, new Paging(0, pageSize), args, sorting);
    }

    static useSuspense(args?: ObserveParameters, sorting?: Sorting): [QueryResultWithState<Listing[]>, SetSorting] {
        return useSuspenseObservableQuery<Listing[], Observe, ObserveParameters>(Observe, args, sorting);
    }

    static useSuspenseWithPaging(pageSize: number, args?: ObserveParameters, sorting?: Sorting): [QueryResultWithState<Listing[]>, SetSorting, SetPage, SetPageSize] {
        return useSuspenseObservableQueryWithPaging<Listing[], Observe>(Observe, new Paging(0, pageSize), args, sorting);
    }

    static useChangeStream(args?: ObserveParameters, getKey?: (item: Listing) => unknown, sorting?: Sorting): ChangeSet<Listing> {
        return useChangeStream<Listing, Observe, ObserveParameters>(Observe, args, getKey, sorting);
    }

    static when(condition: boolean): ObservableQueryWhen<Observe, Listing[], ObserveParameters> {
        return new ObservableQueryWhen<Observe, Listing[], ObserveParameters>(Observe, condition);
    }
}
