// @generated by Cratis. Source: ProxyComparison.Register. Time: 2026-10-02T14:53:03.8240000Z. Hash: 9213A3CE667705E870E1AA87B3482F81F37362E3416D33C9BE11229F6762AC41
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command, CommandValidator } from '@cratis/arc/commands';
import { useCommand, type SetCommandValues, type ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';
import { Guid } from '@cratis/fundamentals';

export interface IRegister {
    id?: Guid;
    name?: string;
    quantity?: number;
}

export class RegisterValidator extends CommandValidator<IRegister> {
    constructor() {
        super();
        this.ruleFor(c => c.name).notEmpty().withMessage('Name required');
        this.ruleFor(c => c.name).maxLength(40).withMessage('Name too long');
        this.ruleFor(c => c.quantity).greaterThanOrEqual(1).withMessage('Quantity must be positive');
    }
}

export class Register extends Command<IRegister> implements IRegister {
    readonly route: string = '/api/proxy-comparison/register';
    readonly validation: CommandValidator = new RegisterValidator();
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('id', Guid, false),
        new PropertyDescriptor('name', String, false),
        new PropertyDescriptor('quantity', Number, false),
    ];

    private _id!: Guid;
    private _name!: string;
    private _quantity!: number;

    constructor() {
        super(Object, false);
    }

    get requestParameters(): string[] { return []; }

    get id(): Guid {
        return this._id;
    }

    set id(value: Guid) {
        this._id = value;
        this.propertyChanged('id');
    }

    get name(): string {
        return this._name;
    }

    set name(value: string) {
        this._name = value;
        this.propertyChanged('name');
    }

    get quantity(): number {
        return this._quantity;
    }

    set quantity(value: number) {
        this._quantity = value;
        this.propertyChanged('quantity');
    }

    static use(initialValues?: IRegister): [Register, SetCommandValues<IRegister>, ClearCommandValues] {
        return useCommand<Register, IRegister>(Register, initialValues);
    }
}
