// @generated by Cratis. Source: ProxyComparison.Status. Time: 2026-10-02T15:23:26.2870000Z. Hash: D6BE2F44AEE3F50AB357446E1374EEC78C1ABC0A6A249AADA64C9DC7327939E2
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

// eslint-disable-next-line header/header
export enum Status {
    Draft = 0,
    Published = 1,
}
