// @generated by Cratis. Source: ProxyComparison.UrgentNotice. Time: 2026-10-02T14:53:03.8250000Z. Hash: E68232937A2D329A758BE7A911099151B8188944D1CDE443CF39C4FF54CB4C7F
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { derivedType, field } from '@cratis/fundamentals';
import { Notice } from './Notice';

@derivedType('1578f20a-cd63-456f-98aa-c97daf05d0fa')
export class UrgentNotice extends Notice {
    @field(Number)
    priority!: number;
}
