// @generated by Cratis. Source: ProxyComparison.Listing. Time: 2026-10-02T14:53:03.4849190Z. Hash: 0E155A2217FA241EB7A3F167FC3C62571830874898B0B657D2366B8EA0B3AE01
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { QueryFor, QueryResultWithState, Sorting, SortingActions, SortingActionsForQuery, Paging } from '@cratis/arc/queries';
import { useQuery, useQueryWithPaging, useSuspenseQuery, useSuspenseQueryWithPaging, PerformQuery, SetSorting, SetPage, SetPageSize, QueryWhen } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { Guid } from '@cratis/fundamentals';
import { Listing } from './Listing';

class AllSortBy {
    private _id: SortingActionsForQuery<Listing[]>;

    constructor(readonly query: All) {
        this._id = new SortingActionsForQuery<Listing[]>('id', query);
    }

    get id(): SortingActionsForQuery<Listing[]> {
        return this._id;
    }
}

class AllSortByWithoutQuery {
    private _id: SortingActions  = new SortingActions('id');

    get id(): SortingActions {
        return this._id;
    }
}

export interface AllParameters {
    id: Guid;
}


export class All extends QueryFor<Listing[], AllParameters> {
    readonly route: string = '/api/proxy-comparison/all';
    readonly queryName: string = 'ProxyComparison.Listing.All';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: Listing[] = [];
    private readonly _sortBy: AllSortBy;
    private static readonly _sortBy: AllSortByWithoutQuery = new AllSortByWithoutQuery();

    constructor() {
        super(Listing, true);
        this._sortBy = new AllSortBy(this);
    }

    get requiredRequestParameters(): string[] {
        return [
            'id',
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
        new ParameterDescriptor('id', Guid, false),
    ];

    id!: Guid;

    get sortBy(): AllSortBy {
        return this._sortBy;
    }

    static get sortBy(): AllSortByWithoutQuery {
        return this._sortBy;
    }

    static use(args?: AllParameters, sorting?: Sorting): [QueryResultWithState<Listing[]>, PerformQuery<AllParameters>, SetSorting] {
        return useQuery<Listing[], All, AllParameters>(All, args, sorting);
    }

    static useWithPaging(pageSize: number, args?: AllParameters, sorting?: Sorting): [QueryResultWithState<Listing[]>, PerformQuery, SetSorting, SetPage, SetPageSize] {
        return useQueryWithPaging<Listing[], All>(All, new Paging(0, pageSize), args, sorting);
    }

    static useSuspense(args?: AllParameters, sorting?: Sorting): [QueryResultWithState<Listing[]>, PerformQuery<AllParameters>, SetSorting] {
        return useSuspenseQuery<Listing[], All, AllParameters>(All, args, sorting);
    }

    static useSuspenseWithPaging(pageSize: number, args?: AllParameters, sorting?: Sorting): [QueryResultWithState<Listing[]>, PerformQuery, SetSorting, SetPage, SetPageSize] {
        return useSuspenseQueryWithPaging<Listing[], All>(All, new Paging(0, pageSize), args, sorting);
    }

    static when(condition: boolean): QueryWhen<All, Listing[], AllParameters> {
        return new QueryWhen<All, Listing[], AllParameters>(All, condition);
    }
}
