// @generated by Cratis. Source: ProxyComparison.Detail. Time: 2026-10-02T14:53:03.4896860Z. Hash: 870244FDEBCE32A475902C261DDFF3AEADEFBA1A0B20D5FA623D6D1BD7473F94
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { field } from '@cratis/fundamentals';
import { Guid } from '@cratis/fundamentals';

export class Detail {
    @field(Guid)
    id!: Guid;
    @field(Date)
    created!: Date;
}
