// @generated by Cratis. Source: ProxyComparison.Listing. Time: 2026-10-02T15:23:25.9691550Z. Hash: 5E26E7FA2DA1134B949B271ED9019A0867B1FE2121E2BE76E9D4904F1F537957
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { field } from '@cratis/fundamentals';
import { Detail } from './Detail';
import { Notice } from './Notice';
import { Status } from './Status';

export class Listing {
    @field(String)
    name!: string;
    @field(Detail)
    detail!: Detail;
    @field(Notice)
    notice!: Notice;
    @field(Number)
    status!: Status;
}
