// @generated by Cratis. Source: ProxyComparison.Listing. Time: 2026-10-02T14:53:03.4865950Z. Hash: 37AEFC99489891A80968EA738258F7C8759C9732BDCB0FD063B4C85F15651914
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { ObservableQueryFor, QueryResultWithState, Sorting, SortingActions, SortingActionsForObservableQuery, Paging, ChangeSet } from '@cratis/arc/queries';
import { useObservableQuery, useObservableQueryWithPaging, useSuspenseObservableQuery, useSuspenseObservableQueryWithPaging, useChangeStream, SetSorting, SetPage, SetPageSize, ObservableQueryWhen } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { Guid } from '@cratis/fundamentals';
import { Listing } from './Listing';

class ObserveSortBy {
    private _id: SortingActionsForObservableQuery<Listing[]>;

    constructor(readonly query: Observe) {
        this._id = new SortingActionsForObservableQuery<Listing[]>('id', query);
    }

    get id(): SortingActionsForObservableQuery<Listing[]> {
        return this._id;
    }
}

class ObserveSortByWithoutQuery {
    private _id: SortingActions  = new SortingActions('id');

    get id(): SortingActions {
        return this._id;
    }
}

export interface ObserveParameters {

    id: Guid;
}


export class Observe extends ObservableQueryFor<Listing[], ObserveParameters> {
    readonly route: string = '/api/proxy-comparison/observe';
    readonly queryName: string = 'ProxyComparison.Listing.Observe';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: Listing[] = [];
    private readonly _sortBy: ObserveSortBy;
    private static readonly _sortBy: ObserveSortByWithoutQuery = new ObserveSortByWithoutQuery();

    constructor() {
        super(Listing, true);
        this._sortBy = new ObserveSortBy(this);
    }

    get requiredRequestParameters(): string[] {
        return [
            'id',
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
        new ParameterDescriptor('id', Guid, false),
    ];

    id!: Guid;

    get sortBy(): ObserveSortBy {
        return this._sortBy;
    }

    static get sortBy(): ObserveSortByWithoutQuery {
        return this._sortBy;
    }

    static use(args?: ObserveParameters, sorting?: Sorting): [QueryResultWithState<Listing[]>, SetSorting] {
        return useObservableQuery<Listing[], Observe, ObserveParameters>(Observe, args, sorting);
    }

    static useWithPaging(pageSize: number, args?: ObserveParameters, sorting?: Sorting): [QueryResultWithState<Listing[]>, SetSorting, SetPage, SetPageSize] {
        return useObservableQueryWithPaging<Listing[], Observe>(Observe, new Paging(0, pageSize), args, sorting);
    }

    static useSuspense(args?: ObserveParameters, sorting?: Sorting): [QueryResultWithState<Listing[]>, SetSorting] {
        return useSuspenseObservableQuery<Listing[], Observe, ObserveParameters>(Observe, args, sorting);
    }

    static useSuspenseWithPaging(pageSize: number, args?: ObserveParameters, sorting?: Sorting): [QueryResultWithState<Listing[]>, SetSorting, SetPage, SetPageSize] {
        return useSuspenseObservableQueryWithPaging<Listing[], Observe>(Observe, new Paging(0, pageSize), args, sorting);
    }

    static useChangeStream(args?: ObserveParameters, getKey?: (item: Listing) => unknown, sorting?: Sorting): ChangeSet<Listing> {
        return useChangeStream<Listing, Observe, ObserveParameters>(Observe, args, getKey, sorting);
    }

    static when(condition: boolean): ObservableQueryWhen<Observe, Listing[], ObserveParameters> {
        return new ObservableQueryWhen<Observe, Listing[], ObserveParameters>(Observe, condition);
    }
}
