// @generated by Cratis. Source: ProxyComparison.Register. Time: 2026-10-02T15:23:25.9473890Z. Hash: 1D6FE14590B481D913125C1B2BE21D724F94D8AABAB561D47058830A6CADC8E2
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command, CommandValidator } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';
import { Guid } from '@cratis/fundamentals';

export interface IRegister {
    id?: Guid;
    name?: string;
    quantity?: number;
}

export class RegisterValidator extends CommandValidator<IRegister> {
    constructor() {
        super();
        this.ruleFor(c => c.name).notEmpty().withMessage('Name required');
        this.ruleFor(c => c.name).maxLength(40).withMessage('Name too long');
        this.ruleFor(c => c.quantity).greaterThanOrEqual(1).withMessage('Quantity must be positive');
    }
}

export class Register extends Command<IRegister> implements IRegister {
    readonly route: string = '/api/proxy-comparison/register';
    readonly validation: CommandValidator = new RegisterValidator();
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('id', Guid, false),
        new PropertyDescriptor('name', String, false),
        new PropertyDescriptor('quantity', Number, false),
    ];

    private _id!: Guid;
    private _name!: string;
    private _quantity!: number;

    constructor() {
        super(Object, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    get id(): Guid {
        return this._id;
    }

    set id(value: Guid) {
        this._id = value;
        this.propertyChanged('id');
    }
    get name(): string {
        return this._name;
    }

    set name(value: string) {
        this._name = value;
        this.propertyChanged('name');
    }
    get quantity(): number {
        return this._quantity;
    }

    set quantity(value: number) {
        this._quantity = value;
        this.propertyChanged('quantity');
    }

    static use(initialValues?: IRegister): [Register, SetCommandValues<IRegister>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<Register, IRegister>(Register, initialValues);
    }
}
