// @generated by Cratis. Source: ProxyComparison.UrgentNotice. Time: 2026-10-02T14:53:03.4896860Z. Hash: B6DFD0F8172730462EE16C33D07A74E01C2C446E0DC8E33AF2A92DF22C4B1738
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { field, derivedType } from '@cratis/fundamentals';
import { Notice } from './Notice';

@derivedType('1578f20a-cd63-456f-98aa-c97daf05d0fa')
export class UrgentNotice extends Notice {
    @field(Number)
    priority!: number;
}
