// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
// @generated by Cratis. Regenerate with arc-proxygenerator --metadata. Hash: ebf45f64ef1d50f587619b1baf335d037f375e70dca26f044537395e3c1502ad
import { type GeneratedMetadata } from '@cratis/arc.core';
import { TaskItem as _arc0 } from "./Tasks/Listing/TaskItem.js";
import { TaskId as _arc1 } from "./Tasks/TaskId.js";
import { Tasks as _arc2 } from "./Tasks/Tasks.js";
import { RegisterTask as _arc3 } from "./Tasks/Registration/RegisterTask.js";
import { RegisterTaskValidator as _arc4 } from "./Tasks/Registration/RegisterTaskValidator.js";
import { TaskTitleValidator as _arc5 } from "./Tasks/TaskTitleValidator.js";
import { TaskTitle as _arc6 } from "./Tasks/TaskTitle.js";

export const metadata = { version: 1, artifacts: [
    { type: _arc0, signature: "{\"name\":\"TaskItem\",\"fields\":[[\"id\",\"TaskId\"],[\"title\",\"TaskTitle\"]],\"handle\":null,\"provide\":null,\"queries\":[[\"allTasks\",1],[\"observeAllTasks\",1],[\"taskById\",2]]}", metadata: { readModel: true, queryMethods: new Map([["allTasks", { parameters: undefined, generated: false, observable: false, result: { cardinality: 'many', nullable: false, element: _arc0 } }], ["taskById", { parameters: [{ kind: 'argument', name: "id", type: _arc1, optional: false }, { kind: 'service', token: _arc2 }], generated: true, observable: false, result: { cardinality: 'one', nullable: true, element: _arc0 } }], ["observeAllTasks", { parameters: [{ kind: 'service', token: _arc2 }], generated: true, observable: true, result: { cardinality: 'many', nullable: false, element: _arc0 } }]]), fieldOptions: new Map(Object.entries({ "id": { optional: false, nullable: false }, "title": { optional: false, nullable: false } })), } },
    { type: _arc3, signature: "{\"name\":\"RegisterTask\",\"fields\":[[\"id\",\"TaskId\"],[\"title\",\"TaskTitle\"]],\"handle\":1,\"provide\":null,\"queries\":[]}", metadata: { command: true, handleResult: { cardinality: 'one', nullable: false, element: _arc1 }, generatedBindings: true, injected: new Map([['handle', [_arc2]]]), fieldOptions: new Map(Object.entries({ "id": { optional: false, nullable: false }, "title": { optional: false, nullable: false } })), } },
    { type: _arc4, signature: "{\"name\":\"RegisterTaskValidator\",\"fields\":[],\"handle\":null,\"provide\":null,\"queries\":[]}", metadata: { validatorTarget: _arc3, } },
    { type: _arc5, signature: "{\"name\":\"TaskTitleValidator\",\"fields\":[],\"handle\":null,\"provide\":null,\"queries\":[]}", metadata: { validatorTarget: _arc6, } }
] } satisfies GeneratedMetadata;
