// @generated by Cratis. Source: Tasks.Listing.TaskItem.allTasks. Time: 2026-09-27T07:37:31.8280000Z. Hash: 4C1DD833A1D8EE6F82B72AAA661800907E990D1E7CB64550F729FB39AD12ADF9
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { QueryFor, type QueryResultWithState, type Sorting, Paging, SortingActions, SortingActionsForQuery } from '@cratis/arc/queries';
import { useQuery, useSuspenseQuery, useQueryWithPaging, useSuspenseQueryWithPaging, type SetPage, type SetPageSize, type PerformQuery, type SetSorting, QueryWhen } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { TaskItem } from './TaskItem.proxy';

class AllTasksSortBy {
    readonly id: SortingActionsForQuery<TaskItem[]>;
    readonly title: SortingActionsForQuery<TaskItem[]>;
    constructor(readonly query: AllTasks) {
        this.id = new SortingActionsForQuery<TaskItem[]>('id', query);
        this.title = new SortingActionsForQuery<TaskItem[]>('title', query);
    }
}
class AllTasksSortByWithoutQuery {
    readonly id = new SortingActions('id');
    readonly title = new SortingActions('title');
}

export class AllTasks extends QueryFor<TaskItem[]> {
    readonly route: string = '/api/tasks/listing/all-tasks';
    readonly queryName: string = 'Tasks.Listing.TaskItem.allTasks';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: TaskItem[] = [];
    private readonly _sortBy: AllTasksSortBy;
    private static readonly _sortBy: AllTasksSortByWithoutQuery = new AllTasksSortByWithoutQuery();

    constructor() {
        super(TaskItem, true);
        this._sortBy = new AllTasksSortBy(this);
    }

    get requiredRequestParameters(): string[] {
        return [

        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [

    ];

    get sortBy(): AllTasksSortBy { return this._sortBy; }
    static get sortBy(): AllTasksSortByWithoutQuery { return this._sortBy; }

    static use(sorting?: Sorting): [QueryResultWithState<TaskItem[]>, PerformQuery, SetSorting] {
        return useQuery<TaskItem[], AllTasks>(AllTasks, undefined, sorting);
    }

    static useWithPaging(pageSize: number, sorting?: Sorting): [QueryResultWithState<TaskItem[]>, PerformQuery, SetSorting, SetPage, SetPageSize] {
        return useQueryWithPaging<TaskItem[], AllTasks>(AllTasks, new Paging(0, pageSize), undefined, sorting);
    }

    static useSuspense(sorting?: Sorting): [QueryResultWithState<TaskItem[]>, PerformQuery, SetSorting] {
        return useSuspenseQuery<TaskItem[], AllTasks>(AllTasks, undefined, sorting);
    }

    static useSuspenseWithPaging(pageSize: number, sorting?: Sorting): [QueryResultWithState<TaskItem[]>, PerformQuery, SetSorting, SetPage, SetPageSize] {
        return useSuspenseQueryWithPaging<TaskItem[], AllTasks>(AllTasks, new Paging(0, pageSize), undefined, sorting);
    }

    static when(condition: boolean): QueryWhen<AllTasks, TaskItem[]> {
        return new QueryWhen<AllTasks, TaskItem[]>(AllTasks, condition);
    }
}
