// @generated by Cratis. Source: Tasks.Listing.TaskItem.observeAllTasks. Time: 2026-09-27T07:37:31.8340000Z. Hash: 56E5A6EA9AC128841C1BA431C3F3A86068D7FC1AB9DBA5554304F206B70FD00E
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { ObservableQueryFor, type QueryResultWithState, type Sorting, Paging, SortingActions, SortingActionsForObservableQuery, type ChangeSet } from '@cratis/arc/queries';
import { useObservableQuery, useSuspenseObservableQuery, useObservableQueryWithPaging, useSuspenseObservableQueryWithPaging, type SetPage, type SetPageSize, useChangeStream, type SetSorting, ObservableQueryWhen } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { TaskItem } from './TaskItem.proxy';

class ObserveAllTasksSortBy {
    readonly id: SortingActionsForObservableQuery<TaskItem[]>;
    readonly title: SortingActionsForObservableQuery<TaskItem[]>;
    constructor(readonly query: ObserveAllTasks) {
        this.id = new SortingActionsForObservableQuery<TaskItem[]>('id', query);
        this.title = new SortingActionsForObservableQuery<TaskItem[]>('title', query);
    }
}
class ObserveAllTasksSortByWithoutQuery {
    readonly id = new SortingActions('id');
    readonly title = new SortingActions('title');
}

export class ObserveAllTasks extends ObservableQueryFor<TaskItem[]> {
    readonly route: string = '/api/tasks/listing/observe-all-tasks';
    readonly queryName: string = 'Tasks.Listing.TaskItem.observeAllTasks';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: TaskItem[] = [];
    private readonly _sortBy: ObserveAllTasksSortBy;
    private static readonly _sortBy: ObserveAllTasksSortByWithoutQuery = new ObserveAllTasksSortByWithoutQuery();

    constructor() {
        super(TaskItem, true);
        this._sortBy = new ObserveAllTasksSortBy(this);
    }

    get requiredRequestParameters(): string[] {
        return [

        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [

    ];

    get sortBy(): ObserveAllTasksSortBy { return this._sortBy; }
    static get sortBy(): ObserveAllTasksSortByWithoutQuery { return this._sortBy; }

    static use(sorting?: Sorting): [QueryResultWithState<TaskItem[]>, SetSorting] {
        return useObservableQuery<TaskItem[], ObserveAllTasks>(ObserveAllTasks, undefined, sorting);
    }

    static useWithPaging(pageSize: number, sorting?: Sorting): [QueryResultWithState<TaskItem[]>, SetSorting, SetPage, SetPageSize] {
        return useObservableQueryWithPaging<TaskItem[], ObserveAllTasks>(ObserveAllTasks, new Paging(0, pageSize), undefined, sorting);
    }

    static useSuspense(sorting?: Sorting): [QueryResultWithState<TaskItem[]>, SetSorting] {
        return useSuspenseObservableQuery<TaskItem[], ObserveAllTasks>(ObserveAllTasks, undefined, sorting);
    }

    static useSuspenseWithPaging(pageSize: number, sorting?: Sorting): [QueryResultWithState<TaskItem[]>, SetSorting, SetPage, SetPageSize] {
        return useSuspenseObservableQueryWithPaging<TaskItem[], ObserveAllTasks>(ObserveAllTasks, new Paging(0, pageSize), undefined, sorting);
    }

    static useChangeStream(getKey?: (item: TaskItem) => unknown, sorting?: Sorting): ChangeSet<TaskItem> {
        return useChangeStream<TaskItem, ObserveAllTasks>(ObserveAllTasks, undefined, getKey, sorting);
    }

    static when(condition: boolean): ObservableQueryWhen<ObserveAllTasks, TaskItem[]> {
        return new ObservableQueryWhen<ObserveAllTasks, TaskItem[]>(ObserveAllTasks, condition);
    }
}
