// @generated by Cratis. Source: Tasks.Listing.TaskItem. Time: 2026-09-27T07:37:31.8380000Z. Hash: 64FFCD1027A87C5041BAB73B1804134688266784186BFE911892A19E5E689A93
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { Guid, field } from '@cratis/fundamentals';

export class TaskItem {
    @field(Guid)
    id!: Guid;

    @field(String)
    title!: string;
}
