// @generated by Cratis. Source: Tasks.Listing.TaskItem.taskById. Time: 2026-09-27T07:37:31.8360000Z. Hash: D227378FEAF0150352675A8809CA502C90AA2AB353F1AE5C043534A219E1568E
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { QueryFor, type QueryResultWithState } from '@cratis/arc/queries';
import { useQuery, useSuspenseQuery, type PerformQuery, type SetSorting, QueryWhen } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { Guid } from '@cratis/fundamentals';
import { TaskItem } from './TaskItem.proxy';

export interface TaskByIdParameters {
    id: Guid;
}

export class TaskById extends QueryFor<TaskItem, TaskByIdParameters> {
    readonly route: string = '/api/tasks/listing/task-by-id';
    readonly queryName: string = 'Tasks.Listing.TaskItem.taskById';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: TaskItem = {} as TaskItem;

    constructor() {
        super(TaskItem, false);
    }

    get requiredRequestParameters(): string[] {
        return [
            'id',
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
        new ParameterDescriptor('id', Guid, false),
    ];

    id!: Guid;

    static use(args?: TaskByIdParameters): [QueryResultWithState<TaskItem>, PerformQuery<TaskByIdParameters>, SetSorting] {
        return useQuery<TaskItem, TaskById, TaskByIdParameters>(TaskById, args);
    }

    static useSuspense(args?: TaskByIdParameters): [QueryResultWithState<TaskItem>, PerformQuery<TaskByIdParameters>, SetSorting] {
        return useSuspenseQuery<TaskItem, TaskById, TaskByIdParameters>(TaskById, args);
    }

    static when(condition: boolean): QueryWhen<TaskById, TaskItem, TaskByIdParameters> {
        return new QueryWhen<TaskById, TaskItem, TaskByIdParameters>(TaskById, condition);
    }
}
