// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
import { chmod, link, lstat, readFile, realpath, rename, writeFile, unlink } from 'node:fs/promises';
import { isAbsolute, join, resolve, sep } from 'node:path';
import { randomUUID } from 'node:crypto';
import { validateClientManifest } from '@cratis/arc.server';
import type { ClientField, ClientManifest, ClientOperation, ClientType } from '@cratis/arc.server';

const header = '// Copyright (c) Cratis. All rights reserved.\n// Licensed under the MIT license. See LICENSE file in the project root for full license information.\n// Generated by @cratis/arc.server.codegen; do not edit.\n';
const reserved = new Set(['CON', 'PRN', 'AUX', 'NUL', ...Array.from({ length: 9 }, (_, index) => `COM${index + 1}`), ...Array.from({ length: 9 }, (_, index) => `LPT${index + 1}`)]);
function symbol(name: string): string { return name.split('.').join('_'); }
function literal(value: string): string { return JSON.stringify(value); }
function typeOf(type: ClientType): string {
    if (type.kind === 'void') return 'void';
    if (type.kind === 'dto') return type.name;
    if (type.kind === 'array') return type.element.kind === 'enum' ? `(${typeOf(type.element)})[]` : `${typeOf(type.element)}[]`;
    if (type.kind === 'enum') return type.values.map(literal).join(' | ');
    return type.kind;
}
function ctor(type: ClientType): string {
    if (type.kind === 'array') return ctor(type.element);
    if (type.kind === 'dto') return type.name;
    if (type.kind === 'string' || type.kind === 'enum') return 'String';
    if (type.kind === 'number') return 'Number';
    if (type.kind === 'boolean') return 'Boolean';
    return 'undefined'; // Only an explicitly declared void command reaches here.
}
function properties(fields: readonly ClientField[]): string {
    return fields.map(field => `    ${field.name}${field.optional ? '?' : '!'}: ${typeOf(field.type)};`).join('\n');
}
function dto(type: Extract<ClientType, { kind: 'dto' }>): string {
    const properties = type.fields.map(field => {
        const isArray = field.type.kind === 'array';
        return `    @field(${ctor(field.type)}${isArray ? ', { enumerable: true }' : ''})\n    ${field.name}${field.optional ? '?' : '!'}: ${typeOf(field.type)};`;
    }).join('\n');
    return `${header}import '@cratis/fundamentals/reflection';\nimport { field } from '@cratis/fundamentals';\n\nexport class ${type.name} {\n${properties}\n}\n`;
}
function command(operation: ClientOperation): string {
    const name = symbol(operation.id);
    const output = operation.output;
    const model = output.kind === 'dto' ? output : output.kind === 'array' && output.element.kind === 'dto' ? output.element : undefined;
    const fields = operation.input;
    const descriptors = fields.map(field => `        new PropertyDescriptor(${literal(field.name)}, ${ctor(field.type)}, ${field.optional === true})`).join(',\n');
    return `${header}import { Command } from '@cratis/arc/commands';\nimport { PropertyDescriptor } from '@cratis/arc/reflection';\n${model ? `import { ${model.name} } from './${model.name}.proxy.js';\n` : ''}\nexport interface I${name} {\n${fields.map(field => `    ${field.name}${field.optional ? '?' : ''}: ${typeOf(field.type)};`).join('\n')}\n}\n\nexport class ${name} extends Command<I${name}, ${typeOf(output)}> implements I${name} {\n    readonly route = ${literal(operation.route)};\n    readonly roles: string[] = ${JSON.stringify(operation.roles)};\n    readonly propertyDescriptors: PropertyDescriptor[] = [\n${descriptors}\n    ];\n${properties(fields)}\n    constructor() { super(${ctor(output)}, ${output.kind === 'array'}); }\n    get requestParameters(): string[] { return []; }\n}\n`;
}
function query(operation: ClientOperation): string {
    const name = symbol(operation.id);
    const output = operation.output;
    const model = output.kind === 'dto' ? output : output.kind === 'array' && output.element.kind === 'dto' ? output.element : undefined;
    const descriptors = operation.input.map(field => `        new ParameterDescriptor(${literal(field.name)}, ${ctor(field.type)}, ${field.type.kind === 'array'})`).join(',\n');
    const required = operation.input.filter(field => !field.optional).map(field => field.name);
    const defaultValue = output.kind === 'array' ? '[]' : `new ${ctor(output)}()`;
    const base = operation.kind === 'observable' ? 'ObservableQueryFor' : 'QueryFor';
    return `${header}import { ${base}${operation.methods.length === 1 ? ', QueryHttpMethod' : ''} } from '@cratis/arc/queries';\nimport { ParameterDescriptor } from '@cratis/arc/reflection';\n${model ? `import { ${model.name} } from './${model.name}.proxy.js';\n` : ''}\nexport interface ${name}Parameters {\n${operation.input.map(field => `    ${field.name}${field.optional ? '?' : ''}: ${typeOf(field.type)};`).join('\n')}\n}\n\nexport class ${name} extends ${base}<${typeOf(output)}, ${name}Parameters> {\n    readonly route = ${literal(operation.route)};\n    readonly queryName = ${literal(operation.queryName!)};\n    readonly roles: string[] = ${JSON.stringify(operation.roles)};\n    readonly defaultValue: ${typeOf(output)} = ${defaultValue};\n    readonly parameterDescriptors: ParameterDescriptor[] = [\n${descriptors}\n    ];\n    constructor() { super(${ctor(output)}, ${output.kind === 'array'});${operation.methods.length === 1 ? ' this.setHttpMethod(QueryHttpMethod.Get);' : ''} }\n    get requiredRequestParameters(): string[] { return ${JSON.stringify(required)}; }\n}\n`;
}
/** Pure rendering: all descriptors are validated before producing any output. */
export function renderClientManifest(input: unknown): ReadonlyMap<string, string> {
    const manifest: ClientManifest = validateClientManifest(input);
    const files = new Map<string, string>();
    const folded = new Set<string>();
    const add = (file: string, content: string): void => {
        const base = file.replace(/\.proxy\.ts$/, '');
        if (reserved.has(base.toUpperCase()) || folded.has(file.toLowerCase()) || base === '.' || base === '..') throw new Error(`Client generation filename collision: ${file}`);
        folded.add(file.toLowerCase()); files.set(file, content);
    };
    const dtos = new Map<string, Extract<ClientType, { kind: 'dto' }>>();
    const generatedSymbols = new Set(manifest.operations.flatMap(operation => {
        const name = symbol(operation.id).toLowerCase();
        return [name, `i${name}`, `${name}parameters`];
    }));
    for (const operation of manifest.operations) {
        const output = operation.output;
        const model = output.kind === 'dto' ? output : output.kind === 'array' && output.element.kind === 'dto' ? output.element : undefined;
        if (model) {
            if (generatedSymbols.has(model.name.toLowerCase())) throw new Error(`Client DTO conflicts with generated symbol: ${model.name}`);
            const previous = dtos.get(model.name.toLowerCase());
            if (previous && JSON.stringify(previous) !== JSON.stringify(model)) throw new Error(`Conflicting client DTO: ${model.name}`);
            dtos.set(model.name.toLowerCase(), model);
        }
        add(`${symbol(operation.id)}.proxy.ts`, operation.kind === 'command' ? command(operation) : query(operation));
    }
    for (const model of [...dtos.values()].sort((a, b) => a.name < b.name ? -1 : a.name > b.name ? 1 : 0)) add(`${model.name}.proxy.ts`, dto(model));
    return new Map([...files].sort(([a], [b]) => a < b ? -1 : a > b ? 1 : 0));
}
/** No discovery imports: caller provides a JSON manifest and an existing, explicitly chosen output root. */
export async function generateClient(input: unknown, outputRoot: string): Promise<readonly string[]> {
    const files = renderClientManifest(input); // Complete validation before touching the filesystem.
    if (!isAbsolute(outputRoot) || outputRoot.includes('\0')) throw new Error('Client output root must be an absolute path');
    const root = resolve(outputRoot);
    const rootStat = await lstat(root);
    if (!rootStat.isDirectory() || rootStat.isSymbolicLink() || await realpath(root) !== root) throw new Error('Client output root must be an existing real directory');
    const changed: { path: string; content: string; prior?: string; mode: number }[] = [];
    for (const [file, content] of files) {
        const path = join(root, file);
        if (!path.startsWith(root + sep) || file.includes('/') || file.includes('\\')) throw new Error(`Client output escape: ${file}`);
        try {
            const stat = await lstat(path);
            if (!stat.isFile() || stat.isSymbolicLink()) throw new Error(`Client output is not a regular file: ${file}`);
            const existing = await readFile(path, 'utf8');
            if (!existing.startsWith(header)) throw new Error(`Refusing to overwrite handwritten file: ${file}`);
            if (existing !== content) changed.push({ path, content, prior: existing, mode: stat.mode & 0o777 });
        } catch (error) {
            if (!(error instanceof Error) || !('code' in error) || error.code !== 'ENOENT') throw error;
            changed.push({ path, content, mode: 0o666 & ~process.umask() });
        }
    }
    const pending: { temp: string; item: { path: string; content: string; prior?: string; mode: number } }[] = [];
    const committed: string[] = [];
    try {
        for (const item of changed) {
            const temp = join(root, `.arc-server-${randomUUID()}.tmp`);
            await writeFile(temp, item.content, { flag: 'wx', mode: 0o600 });
            pending.push({ temp, item });
            await chmod(temp, item.mode);
        }
        for (const { temp, item } of pending) {
            const currentRoot = await lstat(root);
            if (!currentRoot.isDirectory() || currentRoot.isSymbolicLink() || currentRoot.dev !== rootStat.dev || currentRoot.ino !== rootStat.ino || await realpath(root) !== root)
                throw new Error('Client output root changed during generation');
            let current: string | undefined;
            try {
                const stat = await lstat(item.path);
                if (!stat.isFile() || stat.isSymbolicLink() || (stat.mode & 0o777) !== item.mode) throw new Error(`Client output changed type or mode: ${item.path}`);
                current = await readFile(item.path, 'utf8');
            } catch (error) { if (!(error instanceof Error) || !('code' in error) || error.code !== 'ENOENT') throw error; }
            if (current !== item.prior) throw new Error(`Client output changed during generation: ${item.path}`);
            if (item.prior === undefined) await link(temp, item.path); // Atomic no-clobber publication.
            else await rename(temp, item.path);
            committed.push(item.path);
            if (item.prior === undefined) await unlink(temp);
        }
    } catch (error) {
        const cleanupErrors: unknown[] = [];
        for (const item of pending) { try { await unlink(item.temp); } catch (cleanup) { if (!(cleanup instanceof Error) || !('code' in cleanup) || cleanup.code !== 'ENOENT') cleanupErrors.push(cleanup); } }
        if (committed.length) throw new AggregateError([error, ...cleanupErrors], `Client generation partially committed: ${committed.join(', ')}`, { cause: error });
        if (cleanupErrors.length) throw new AggregateError([error, ...cleanupErrors], 'Client generation and cleanup failed', { cause: error });
        throw error;
    }
    return changed.map(item => item.path);
}
