// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { cp, readFile, readdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { clientTest as test, scratch } from './scratch.mjs';
import { compare, contentPairHash, fingerprintDotnetInputs, stableBytes, verifyDotnetInputs, verifyInventory } from '../ProxyComparison/compare.mjs';
import { dotnetOptions, dotnetSource, fixture, recaptureCommand, root } from '../ProxyComparison/generate.mjs';

test('generated TypeScript and captured .NET proxies retain reviewed bytes and browser contracts without accumulating evidence', async () => {
    const evidence = () => readdir(join(root, '.ai-work/keep/proxy-comparison')).catch(error => {
        if (error.code === 'ENOENT') return [];
        throw error;
    });
    const before = await evidence();
    await compare({ regenerateDotnet: false });
    assert.deepEqual(await evidence(), before, 'Successful comparisons must not write retained evidence');
});

test('the reviewed inventory rejects injected differences in either generator even with valid provenance body hashes', async () => {
    const output = join(await scratch(), 'src');
    await cp(join(fixture, 'Snapshots'), output, { recursive: true });
    const dotnet = join(output, 'DotNET');
    const typescript = join(output, 'TypeScript');
    await verifyInventory(dotnet, typescript);
    // All already has reviewed differences; Notice previously agrees. Both cases need an inventory edit.
    for (const family of ['DotNET', 'TypeScript']) {
        for (const file of ['All.ts', 'Notice.ts']) {
            const path = join(output, family, 'ProxyComparison', file);
            const original = await readFile(path, 'utf8');
            const end = original.indexOf('\n');
            const body = `${original.slice(end + 1)}// Unreviewed change injected in scratch only.\n`;
            const hash = createHash('sha256').update(body).digest('hex').toUpperCase();
            const changed = Buffer.from(`${original.slice(0, end - 64)}${hash}\n${body}`);
            assert.notDeepEqual(stableBytes(changed), stableBytes(Buffer.from(original)));
            try {
                await writeFile(path, changed);
                await assert.rejects(verifyInventory(dotnet, typescript), {
                    code: 'ERR_ASSERTION', message: new RegExp(`${file}: unreviewed difference pair; review and update differences.json`)
                });
            } finally {
                await writeFile(path, original);
            }
        }
    }
});

test('offline provenance rejects changed C# source or .NET options with the recapture command', async () => {
    const source = await readFile(join(root, dotnetSource));
    const { dotnet } = JSON.parse(await readFile(join(fixture, 'provenance.json'), 'utf8'));
    verifyDotnetInputs(dotnet, fingerprintDotnetInputs(source, dotnetOptions));
    for (const changed of [fingerprintDotnetInputs(Buffer.concat([source, Buffer.from('\n')]), dotnetOptions),
        fingerprintDotnetInputs(source, [...dotnetOptions, '--api-prefix=changed']), {}]) {
        assert.throws(() => verifyDotnetInputs(dotnet, changed), error => {
            assert.ok(error.message.includes('Recapture with .NET:'));
            assert.ok(error.message.includes(recaptureCommand));
            return true;
        });
    }
});

test('comparison normalizes only a valid first-line timestamp and rejects body edits', () => {
    const file = (time, body, source = 'Fixture') => Buffer.from(`// @generated by Cratis. Source: ${source}. Time: ${time}. Hash: ${createHash('sha256').update(body).digest('hex').toUpperCase()}\n${body}`);
    const before = '2026-01-01T00:00:00.0000000Z';
    const after = '2026-01-02T00:00:00.0000000Z';
    const body = 'export const value = 1;\n';
    assert.deepEqual(stableBytes(file(before, body)), stableBytes(file(after, body)));
    for (const changed of [body + '\n', body.replace(' = ', '='), body.replace('1', '2'), body.replace('\n', '\r\n')])
        assert.notDeepEqual(stableBytes(file(before, body)), stableBytes(file(after, changed)));
    assert.notDeepEqual(stableBytes(file(before, body)), stableBytes(file(after, body, 'Other')));
    assert.throws(() => stableBytes(Buffer.from(file(before, body).toString().replace('value = 1', 'value = 2'))), /body hash/);
    const unmarked = Buffer.from('export * from "./Fixture";\n');
    assert.deepEqual(stableBytes(unmarked), unmarked);
    assert.equal(contentPairHash(file(before, body), unmarked), contentPairHash(file(after, body), unmarked));
    assert.notEqual(contentPairHash(file(before, body), unmarked), contentPairHash(unmarked, file(before, body)));
});
