// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { execFileSync, spawnSync } from 'node:child_process';
import { cp, lstat, mkdir, readFile, readdir, symlink, unlink, writeFile } from 'node:fs/promises';
import { join, resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
import { Guid } from '@cratis/fundamentals';
import { Globals } from '@cratis/arc';
import { Paging, Sorting, SortDirection, resetSharedMultiplexer } from '@cratis/arc/queries';
import { ArcApplication, AuthenticationStatus } from '@cratis/arc.core';
import { generateFromSource, analyzeSource, renderSource } from '@cratis/arc.proxygenerator';
import { clientTest as test, scratch } from './scratch.mjs';
import { observableHost } from './observableHost.mjs';

const root = resolve(import.meta.dirname, '../..');
const project = join(root, 'Samples/Tasks/tsconfig.json');
const artifacts = join(root, 'Samples/Tasks/Features');
const options = { project, artifacts, useProxyFileSuffix: true, jsImportSpecifiers: true };
async function within(promise, message) {
    let timer;
    try { return await Promise.race([promise, new Promise((_, reject) => { timer = setTimeout(() => reject(new Error(message)), 3000); })]); }
    finally { clearTimeout(timer); }
}
async function generated(overrides = {}) {
    const directory = await scratch();
    const output = join(directory, 'src');
    await mkdir(output);
    const changed = await generateFromSource({ ...options, ...overrides, output });
    const registration = `${overrides.segmentsToSkip ? '' : 'Tasks/'}Registration/RegisterTask.proxy.ts`;
    const before = await readFile(join(output, registration), 'utf8');
    assert.deepEqual(await generateFromSource({ ...options, ...overrides, output }), []);
    assert.equal(await readFile(join(output, registration), 'utf8'), before);
    const tsconfig = { compilerOptions: { target: 'ES2022', module: 'ESNext', moduleResolution: 'Bundler', strict: true,
        skipLibCheck: false, noEmitOnError: true, outDir: './dist', rootDir: './src', types: ['node'] }, include: ['src/**/*.ts'] };
    await writeFile(join(directory, 'tsconfig.json'), JSON.stringify(tsconfig));
    execFileSync(join(root, 'node_modules/.bin/tsc'), ['-p', join(directory, 'tsconfig.json')], { cwd: root });
    const modules = async path => import(pathToFileURL(join(directory, 'dist', path)).href);
    return { output, changed, modules };
}
test('source analyzer resolves imported decorator symbols, types, routes and stable owned output', async () => {
    const analysis = analyzeSource(project, artifacts);
    assert.deepEqual(analysis.operations.map(item => item.name).sort(), ['RegisterTask', 'allTasks', 'observeAllTasks', 'taskById']);
    assert.equal(analysis.operations.find(item => item.name === 'RegisterTask').result.text, 'Guid');
    assert.deepEqual(analysis.recordedRules.get('Tasks.Registration.RegisterTask').map(rule => rule.kind), ['notEmpty', 'maxLength']);
    assert.ok(analysis.diagnostics.some(message => message.includes('Server-only validator rule on value')));
    const rendered = renderSource(analysis, options);
    assert.match(rendered.get('Tasks/Listing/ObserveAllTasks.proxy.ts'), /ObservableQueryFor<TaskItem\[\]>/);
    assert.match(rendered.get('Tasks/Listing/TaskById.proxy.ts'), /\/api\/tasks\/listing\/task-by-id/);
    assert.match(rendered.get('Tasks/Registration/RegisterTask.proxy.ts'), /ruleFor\(c => c.title\).notEmpty\(\).withMessage\('A title is required'\)/);
    assert.match(renderSource(analysis).get('Tasks/Listing/TaskById.ts'), /from '\.\/TaskItem'/);
    const { output } = await generated();
    const commandFile = await readFile(join(output, 'Tasks/Registration/RegisterTask.proxy.ts'), 'utf8');
    assert.match(commandFile, /propertyChanged\('title'\)/);
    const [header, ...body] = commandFile.split('\n');
    assert.match(header, /^\/\/ @generated by Cratis\. Source: Tasks\.Registration\.RegisterTask\. Time: \d{4}-\d\d-\d\dT\d\d:\d\d:\d\d\.\d{7}Z\. Hash: [A-F0-9]{64}$/);
    assert.equal(header.slice(-64), createHash('sha256').update(body.join('\n')).digest('hex').toUpperCase());
    assert.match(commandFile, /\*\*DO NOT EDIT\*\*/);
    const barrel = await readFile(join(output, 'Tasks/Registration/index.ts'), 'utf8');
    assert.match(barrel, /^\/\/ @generated by Cratis\. Source: .*\nexport \* from '\.\/RegisterTask\.proxy';\n$/);
    const own = join(output, 'Tasks/Listing/AllTasks.proxy.ts');
    await writeFile(own, (await readFile(own, 'utf8')).replace("'/api/tasks/listing/all-tasks'", "'/altered'"));
    await assert.rejects(generateFromSource({ ...options, output }), /edited file/);
    assert.ok((await readdir(join(output, 'Tasks/Listing'))).includes('TaskItem.proxy.ts'));
});

for (const kind of ['express', 'fastify', 'hono']) test(`analyzer-generated published client runs against live model-bound ${kind}`, async () => {
    const { modules } = await generated();
    const { RegisterTask } = await modules('Tasks/Registration/RegisterTask.proxy.js');
    const { AllTasks } = await modules('Tasks/Listing/AllTasks.proxy.js');
    const { TaskById } = await modules('Tasks/Listing/TaskById.proxy.js');
    const { ObserveAllTasks } = await modules('Tasks/Listing/ObserveAllTasks.proxy.js');
    const { Tasks } = await import(join(root, 'Samples/Tasks/dist/Features/Tasks/Tasks.js'));
    const builder = ArcApplication.createBuilder({ development: true, authentication: [() => ({ status: AuthenticationStatus.Authenticated,
        principal: { id: 'client', isAuthenticated: true, roles: [] } })] });
    const { metadata } = await import(join(root, 'Samples/Tasks/dist/Features/generatedMetadata.js'));
    builder.useGeneratedMetadata(metadata);
    builder.services.addSingleton(Tasks);
    await builder.discover(pathToFileURL(join(root, 'Samples/Tasks/dist/Features/')));
    const app = await builder.build();
    const listening = await observableHost(kind, app.server);
    try {
        const id = Guid.create();
        const command = new RegisterTask(); command.setOrigin(listening.origin);
        command.id = id; command.title = 'First';
        const saved = await command.execute();
        assert.equal(saved.isSuccess, true, JSON.stringify(saved));
        const list = new AllTasks(); list.setOrigin(listening.origin);
        const result = await list.perform();
        assert.equal(result.isSuccess, true, JSON.stringify(result));
        assert.equal(result.data[0].title, 'First');
        list.paging = new Paging(0, 1);
        list.sorting = new Sorting('title', SortDirection.ascending);
        assert.equal((await list.perform()).paging.totalItems, 1);
        const byId = new TaskById(); byId.setOrigin(listening.origin);
        assert.equal((await byId.perform({ id })).data.title, 'First');
        const observable = new ObserveAllTasks(); observable.setOrigin(listening.origin);
        assert.equal(observable.queryName, 'Tasks.Listing.TaskItem.observeAllTasks');
        assert.equal((await observable.perform()).data[0].title, 'First');
        const previous = { direct: Globals.queryDirectMode, mode: Globals.observableQueryTransferMode };
        Globals.queryDirectMode = false;
        Globals.observableQueryTransferMode = 'full';
        let subscription;
        try {
            const update = Promise.withResolvers();
            subscription = observable.subscribe(value => { if (value.data?.some(item => item.title === 'Second')) update.resolve(); });
            const sendUpdate = async () => {
                const next = new RegisterTask(); next.setOrigin(listening.origin);
                next.id = Guid.create(); next.title = 'Second';
                if (!(await next.execute()).isSuccess) update.reject(new Error('Hub command failed'));
            };
            const timer = setInterval(() => { void sendUpdate().catch(update.reject); }, 100);
            try { await within(update.promise, 'Hub update timed out'); }
            finally { clearInterval(timer); }
        } finally { subscription?.unsubscribe(); Globals.queryDirectMode = previous.direct; Globals.observableQueryTransferMode = previous.mode; resetSharedMultiplexer(); }
    } finally { await listening.close(); await app.stop(); }
});

test('generated API prefix and namespace skipping match live model-bound routes', async () => {
    const { modules } = await generated({ apiPrefix: 'v2', segmentsToSkip: 1 });
    const { RegisterTask } = await modules('Registration/RegisterTask.proxy.js');
    const { AllTasks } = await modules('Listing/AllTasks.proxy.js');
    const { Tasks } = await import(join(root, 'Samples/Tasks/dist/Features/Tasks/Tasks.js'));
    const builder = ArcApplication.createBuilder({ development: true,
        generatedApis: { routePrefix: 'v2', segmentsToSkipForRoute: 1 } });
    const { metadata } = await import(join(root, 'Samples/Tasks/dist/Features/generatedMetadata.js'));
    builder.useGeneratedMetadata(metadata);
    builder.services.addSingleton(Tasks);
    await builder.discover(pathToFileURL(join(root, 'Samples/Tasks/dist/Features/')));
    const app = await builder.build();
    const listening = await observableHost('express', app.server);
    try {
        const command = new RegisterTask(); command.setOrigin(listening.origin);
        command.id = Guid.create(); command.title = 'Changed route';
        assert.equal(command.route, '/v2/registration/register-task');
        assert.equal((await command.execute()).isSuccess, true);
        const list = new AllTasks(); list.setOrigin(listening.origin);
        assert.equal(list.route, '/v2/listing/all-tasks');
        assert.equal((await list.perform()).data[0].title, 'Changed route');
    } finally { await listening.close(); await app.stop(); }
});

test('recorded portable rules emit a typed browser validator and server-only rules report a diagnostic', async () => {
    const diagnostics = [];
    const rules = new Map([['Tasks.Registration.RegisterTask', [
        { path: ['title'], kind: 'notEmpty', args: [], message: 'Required', clientSafe: true },
        { path: ['title'], kind: 'must', args: [], clientSafe: false },
        { path: ['unknown'], kind: 'notEmpty', args: [], clientSafe: true }
    ]]]);
    const rendered = renderSource(analyzeSource(project, artifacts), { ...options, recordedRules: rules, onDiagnostic: message => diagnostics.push(message) });
    assert.match(rendered.get('Tasks/Registration/RegisterTask.proxy.ts'), /ruleFor\(c => c.title\).notEmpty\(\).withMessage\('Required'\)/);
    assert.ok(diagnostics.some(message => message.includes('Server-only validator rule on value')));
    assert.ok(diagnostics.includes('Server-only validation rule on RegisterTask.title: must'));
    assert.ok(diagnostics.includes('Unsupported validation argument on RegisterTask.unknown: notEmpty'));
    assert.doesNotMatch(rendered.get('Tasks/Registration/RegisterTask.proxy.ts'), /ruleFor\(c => c.unknown\)/);
    await generated({ recordedRules: rules, onDiagnostic: () => undefined });
});

test('stale owned files are removed while handwritten files remain unchanged', async () => {
    const { output } = await generated();
    const manual = join(output, 'manual.ts');
    await writeFile(manual, 'export const manual = true;\n');
    const changed = await generateFromSource({ project: join(root, 'ContractTests/Http/modelBound/tsconfig.json'),
        artifacts: join(root, 'ContractTests/Http/modelBound'), output, useProxyFileSuffix: true });
    assert.ok(changed.some(path => path.endsWith('RegisterTask.proxy.ts')));
    assert.equal(await readFile(manual, 'utf8'), 'export const manual = true;\n');
    assert.ok(!(await readdir(join(output, 'Tasks/Listing'))).includes('TaskItem.proxy.ts'));
});

test('generated barrels prune stale exports and handwritten barrels retain directory and package re-exports', async () => {
    const { output } = await generated();
    const listing = join(output, 'Tasks/Listing/index.ts');
    await writeFile(listing, "export * from './sub';\nexport * from '@cratis/arc';\nexport * from './AllTasks.proxy';\n");
    const changed = await generateFromSource({ project: join(root, 'ContractTests/Http/modelBound/tsconfig.json'),
        artifacts: join(root, 'ContractTests/Http/modelBound'), output, useProxyFileSuffix: true });
    assert.ok(changed.includes(listing));
    assert.equal(await readFile(listing, 'utf8'), "export * from './sub';\nexport * from '@cratis/arc';\n");
    assert.ok(!(await readdir(join(output, 'Tasks/Registration'))).includes('index.ts'));
    assert.deepEqual(await generateFromSource({ project: join(root, 'ContractTests/Http/modelBound/tsconfig.json'),
        artifacts: join(root, 'ContractTests/Http/modelBound'), output, useProxyFileSuffix: true }), []);
});

test('multi-shape source resolves temporal types, string enums, arrays and observable/paged query results', async () => {
    const directory = await scratch();
    const src = join(directory, 'src');
    const features = join(src, 'Features');
    await mkdir(features, { recursive: true });
    await writeFile(join(src, 'tsconfig.json'), JSON.stringify({ compilerOptions: {
        target: 'ES2022', module: 'ESNext', moduleResolution: 'Bundler', strict: true,
        skipLibCheck: false, experimentalDecorators: true
    }, include: ['Features/**/*.ts'] }));
    await writeFile(join(features, 'Shapes.ts'), `import * as arc from '@cratis/arc.core';
import * as fundamentals from '@cratis/fundamentals';
import { readModel, query, path, optional, nullable, enumeration, roles, allowAnonymous, authorize, type QueryPage, queryPage, type ObservableSource } from '@cratis/arc.core';
import { field, Guid, DateOnly, TimeOnly, TimeSpan } from '@cratis/fundamentals';
export enum Status { Open = 'open', Closed = 'closed' }
export class Item { @field(String) title!: string; }
@arc.command({ namespace: 'Shop.Checkout' }) @path('/v1/create')
export class Create { @fundamentals.field(Guid) id!: Guid; @field(Date) created!: Date; @field(DateOnly) date!: DateOnly;
    @field(TimeOnly) time!: TimeOnly; @field(TimeSpan) span!: TimeSpan;
    @optional() @field(Boolean) active?: boolean; @nullable() @field(Boolean) answer!: boolean | null;
    @enumeration(Status) @field(String) state!: Status; @field(Item, true) items!: Item[];
    handle(): void {} }
@roles('reader') @readModel({ namespace: 'Shop.Listing' }) export class Listing {
    @allowAnonymous() @query() static all(): Item[] { return []; }
    @authorize() @query() static paged(): QueryPage<Item> { return queryPage([], 0); }
    @query({ observable: true }) static stream(): AsyncIterable<Item[]> { throw new Error('unused'); }
    @query({ observable: true }) static changes(): ObservableSource<Item[]> { throw new Error('unused'); }
}
`);
    const analysis = analyzeSource(join(src, 'tsconfig.json'), features, 'Ignored');
    assert.deepEqual(analysis.operations.map(operation => operation.name), ['Create', 'all', 'paged', 'stream', 'changes']);
    const command = analysis.operations[0];
    assert.equal(command.namespace, 'Shop.Checkout');
    assert.equal(command.fields.find(field => field.name === 'active').optional, true);
    assert.equal(command.fields.find(field => field.name === 'answer').nullable, true);
    assert.equal(command.fields.find(field => field.name === 'state').type.text, 'Status');
    assert.equal(command.fields.find(field => field.name === 'items').type.text, 'Item[]');
    assert.equal(command.fields.find(field => field.name === 'created').type.text, 'Date');
    for (const type of ['Guid', 'DateOnly', 'TimeOnly', 'TimeSpan'])
        assert.equal(command.fields.find(field => field.type.text === type).type.package, '@cratis/fundamentals');
    assert.equal(analysis.operations[1].roles.length, 0);
    assert.equal(analysis.operations[2].roles.length, 0);
    assert.equal(analysis.operations[2].result.enumerable, true);
    assert.equal(analysis.operations[3].kind, 'observable');
    assert.equal(analysis.operations[4].kind, 'observable');
    const rendered = renderSource(analysis, { apiPrefix: 'v2', segmentsToSkip: 1 });
    assert.match(rendered.get('Checkout/Create.ts'), /'\/v1\/create'/);
    assert.match(rendered.get('Listing/Paged.ts'), /'\/v2\/listing\/paged'/);
    assert.match(rendered.get('Status.ts'), /Open = 'open'/);
    assert.match(rendered.get('Checkout/Create.ts'), /get answer\(\): boolean \| null/);
    const output = join(src, 'proxies');
    await mkdir(output);
    await generateFromSource({ project: join(src, 'tsconfig.json'), artifacts: features, output });
    await writeFile(join(src, 'tsconfig.json'), JSON.stringify({ compilerOptions: {
        target: 'ES2022', module: 'ESNext', moduleResolution: 'Bundler', strict: true,
        skipLibCheck: false, experimentalDecorators: true, noEmit: true, types: ['node']
    }, include: ['Features/**/*.ts', 'proxies/**/*.ts'] }));
    const compiled = spawnSync(join(root, 'node_modules/.bin/tsc'), ['-p', join(src, 'tsconfig.json')], { cwd: root, encoding: 'utf8' });
    assert.equal(compiled.status, 0, compiled.stdout + compiled.stderr);
    const interfaces = join(src, 'interfaces'); await mkdir(interfaces);
    await generateFromSource({ project: join(src, 'tsconfig.json'), artifacts: features, output: interfaces, emitInterfaces: true });
    assert.match(await readFile(join(interfaces, 'Item.ts'), 'utf8'), /export interface Item/);
    assert.doesNotMatch(await readFile(join(interfaces, 'Item.ts'), 'utf8'), /@field/);
    await writeFile(join(src, 'tsconfig.json'), JSON.stringify({ compilerOptions: {
        target: 'ES2022', module: 'ESNext', moduleResolution: 'Bundler', strict: true,
        skipLibCheck: false, experimentalDecorators: true, noEmit: true, types: ['node'], verbatimModuleSyntax: true
    }, include: ['Features/**/*.ts', 'interfaces/**/*.ts'] }));
    const interfaceCompile = spawnSync(join(root, 'node_modules/.bin/tsc'), ['-p', join(src, 'tsconfig.json')], { cwd: root, encoding: 'utf8' });
    assert.equal(interfaceCompile.status, 0, interfaceCompile.stdout + interfaceCompile.stderr);
});

test('edited generated barrels are not overwritten or deleted', async () => {
    const { output } = await generated();
    const barrel = join(output, 'Tasks/Listing/index.ts');
    await writeFile(barrel, (await readFile(barrel, 'utf8')).replace("export * from './AllTasks.proxy';", "export * from './manual';"));
    await assert.rejects(generateFromSource({ ...options, output }), /edited generated barrel/);
});

test('symlinks inside output are refused before generation changes files', async () => {
    const { output } = await generated();
    const link = join(output, 'unsafe.ts');
    await symlink(join(output, 'Tasks/Registration/RegisterTask.proxy.ts'), link);
    try { await assert.rejects(generateFromSource({ ...options, output }), /Symlink in output/); }
    finally { await unlink(link); }
});

test('installed non-symlinked Arc package resolves decorators and root namespace', async () => {
    const directory = await scratch();
    const src = join(directory, 'src');
    const installed = join(src, 'node_modules/@cratis/arc.core');
    const features = join(src, 'Features');
    await mkdir(features, { recursive: true });
    await mkdir(installed, { recursive: true });
    await cp(join(root, 'Source/Core/package.json'), join(installed, 'package.json'));
    await cp(join(root, 'Source/Core/dist'), join(installed, 'dist'), { recursive: true,
        filter: path => !path.endsWith('.tsbuildinfo') });
    assert.equal((await lstat(installed)).isSymbolicLink(), false);
    await writeFile(join(src, 'tsconfig.json'), JSON.stringify({ compilerOptions: {
        target: 'ES2022', module: 'ESNext', moduleResolution: 'Bundler', strict: true,
        skipLibCheck: true, experimentalDecorators: true
    }, include: ['Features/**/*.ts'] }));
    await writeFile(join(features, 'Create.ts'), `import { command } from '@cratis/arc.core';\n@command() class Hidden { handle(): void {} }\n@command() export class Create { handle(): void {} }\n`);
    await mkdir(join(features, 'given'));
    await writeFile(join(features, 'given/Fixtures.ts'), `import { command } from '@cratis/arc.core';\n@command() export class Fixtures { handle(): void {} }\n`);
    await writeFile(join(features, 'index.ts'), `import { command } from '@cratis/arc.core';\n@command() export class IndexArtifact { handle(): void {} }\n`);
    const analysis = analyzeSource(join(src, 'tsconfig.json'), features, 'Shop');
    assert.deepEqual(analysis.operations.map(item => [item.name, item.namespace]), [['Create', 'Shop']]);
    assert.match(renderSource(analysis).get('Shop/Create.ts'), /\/api\/shop\/create/);
});

test('server-required field cannot become optional solely because of TypeScript question token', async () => {
    const directory = await scratch();
    const src = join(directory, 'src');
    const features = join(src, 'Features');
    await mkdir(features, { recursive: true });
    await writeFile(join(src, 'tsconfig.json'), JSON.stringify({ compilerOptions: {
        target: 'ES2022', module: 'ESNext', moduleResolution: 'Bundler', strict: true, experimentalDecorators: true
    }, include: ['Features/**/*.ts'] }));
    await writeFile(join(features, 'Broken.ts'), `import { command } from '@cratis/arc.core';\nimport { field } from '@cratis/fundamentals';\n@command() export class Broken { @field(String) note?: string; handle() {} }\n`);
    assert.throws(() => analyzeSource(join(src, 'tsconfig.json'), features), /TypeScript \? disagrees with Arc field optionality/);
});

test('unbound query parameters fail before any files are written', async () => {
    const directory = await scratch();
    const src = join(directory, 'src');
    const features = join(src, 'Features');
    await mkdir(features, { recursive: true });
    await writeFile(join(src, 'tsconfig.json'), JSON.stringify({ compilerOptions: {
        target: 'ES2022', module: 'ESNext', moduleResolution: 'Bundler', strict: true, experimentalDecorators: true
    }, include: ['Features/**/*.ts'] }));
    await writeFile(join(features, 'Broken.ts'), `import { readModel, query } from '@cratis/arc.core';\n@readModel() export class Broken { @query() static search(name: string): string[] { return []; } }\n`);
    assert.throws(() => analyzeSource(join(src, 'tsconfig.json'), features), /unbound query parameter name/);
    assert.throws(() => renderSource({ operations: [{ kind: 'command', name: 'bad-name', owner: 'bad-name', namespace: '',
        roles: [], fields: [], result: { text: 'void', constructor: 'Object', enumerable: false, nullable: false, void: true } }],
        models: [], recordedRules: new Map(), diagnostics: [] }), /Unsafe generated name/);
});

test('CLI accepts equals options, help, root namespace and safe output switches', async () => {
    const directory = await scratch();
    const output = join(directory, 'src'); await mkdir(output);
    const cli = join(root, 'Source/Tools/ProxyGenerator/dist/cli.js');
    const help = spawnSync(process.execPath, [cli, '--help'], { cwd: root, encoding: 'utf8' });
    assert.equal(help.status, 0, help.stderr);
    assert.match(help.stdout, /--emit-interfaces/);
    const generated = spawnSync(process.execPath, [cli, `--project=${project}`, `--artifacts=${artifacts}`, `--output=${output}`,
        '--root-namespace=App', '--api-prefix=v2', '--skip-index-generation', '--skip-output-deletion'], { cwd: root, encoding: 'utf8' });
    assert.equal(generated.status, 0, generated.stderr);
    assert.match(await readFile(join(output, 'App/Tasks/Listing/AllTasks.ts'), 'utf8'), /'\/v2\/app\/tasks\/listing\/all-tasks'/);
    assert.ok(!(await readdir(join(output, 'App/Tasks/Listing'))).includes('index.ts'));
    const missing = spawnSync(process.execPath, [cli, '--project', project, '--artifacts', artifacts, '--output', output,
        '--api-prefix'], { cwd: root, encoding: 'utf8' });
    assert.notEqual(missing.status, 0);
    assert.match(missing.stderr, /Missing value for --api-prefix/);
});

test('invalid source CLI options return nonzero before writing', async () => {
    const directory = await scratch();
    const output = join(directory, 'src'); await mkdir(output);
    const result = spawnSync(process.execPath, [join(root, 'Source/Tools/ProxyGenerator/dist/cli.js'), '--project', project,
        '--artifacts', artifacts, '--output', output, '--segments-to-skip', '-1'], { cwd: root, encoding: 'utf8' });
    assert.notEqual(result.status, 0);
    assert.deepEqual(await readdir(output), []);
});
