// @generated by Cratis. Source: Tasks.Registration.RegisterTask. Time: 2026-09-27T07:37:31.8420000Z. Hash: FDB6670D1623B9F818509BA14942A78DF19A6EDEA92F42D7DD2D75CDB7D04895
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command, CommandValidator } from '@cratis/arc/commands';
import { useCommand, type SetCommandValues, type ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';
import { Guid } from '@cratis/fundamentals';

export interface IRegisterTask {
    id?: Guid;
    title?: string;
}

export class RegisterTaskValidator extends CommandValidator<IRegisterTask> {
    constructor() {
        super();
        this.ruleFor(c => c.title).notEmpty().withMessage('A title is required');
        this.ruleFor(c => c.title).maxLength(100).withMessage('A title can have at most 100 characters');
    }
}

export class RegisterTask extends Command<IRegisterTask, Guid> implements IRegisterTask {
    readonly route: string = '/api/tasks/registration/register-task';
    readonly validation: CommandValidator = new RegisterTaskValidator();
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('id', Guid, false),
        new PropertyDescriptor('title', String, false),
    ];

    private _id!: Guid;
    private _title!: string;

    constructor() {
        super(Guid, false);
    }

    get requestParameters(): string[] { return []; }

    get id(): Guid {
        return this._id;
    }

    set id(value: Guid) {
        this._id = value;
        this.propertyChanged('id');
    }

    get title(): string {
        return this._title;
    }

    set title(value: string) {
        this._title = value;
        this.propertyChanged('title');
    }

    static use(initialValues?: IRegisterTask): [RegisterTask, SetCommandValues<IRegisterTask>, ClearCommandValues] {
        return useCommand<RegisterTask, IRegisterTask>(RegisterTask, initialValues);
    }
}
